//! Registration trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::Registration;

pub type RegistrationTriggerEvent      = TriggerEvent;
pub type RegistrationTriggerContext    = TriggerContext<Registration>;
pub type RegistrationTriggerContextMut = TriggerContextMut<Registration>;
pub type RegistrationActionExecutor    = ActionExecutor;
pub type RegistrationTriggerRegistry   = TriggerRegistry<Registration>;
pub type RegistrationTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<Registration>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for Registration.
pub fn registration_trigger_registry() -> RegistrationTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
