//! EventType DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EventType;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EventType
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEventTypeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "seats_limited")]
    pub seats_limited: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "seats_max")]
    pub seats_max: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "default_date_tz")]
    pub default_date_tz: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_multi_slots")]
    pub is_multi_slots: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EventType
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEventTypeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "seats_limited")]
    pub seats_limited: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "seats_max")]
    pub seats_max: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "default_date_tz")]
    pub default_date_tz: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_multi_slots")]
    pub is_multi_slots: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EventType
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEventTypeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "seats_limited")]
    pub seats_limited: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "seats_max")]
    pub seats_max: Option<i32>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "default_date_tz")]
    pub default_date_tz: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_multi_slots")]
    pub is_multi_slots: Option<bool>,
}

impl PatchEventTypeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.description.is_some() || self.seats_limited.is_some() || self.seats_max.is_some() || self.default_date_tz.is_some() || self.is_multi_slots.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EventType entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EventTypeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub seats_limited: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub seats_max: i32,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub default_date_tz: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_multi_slots: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EventType entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EventTypeListResponseDto {
    /// List of items
    pub items: Vec<EventTypeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EventTypeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EventTypeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EventTypeSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub seats_limited: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EventType> for EventTypeResponseDto {
    fn from(entity: EventType) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            description: entity.description,
            seats_limited: entity.seats_limited,
            seats_max: entity.seats_max,
            default_date_tz: entity.default_date_tz,
            is_multi_slots: entity.is_multi_slots,
            metadata: entity.metadata,
        }
    }
}

impl From<EventType> for EventTypeSummaryDto {
    fn from(entity: EventType) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            description: entity.description,
            seats_limited: entity.seats_limited,
            created_at,
        }
    }
}

impl From<CreateEventTypeDto> for EventType {
    fn from(dto: CreateEventTypeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            description: dto.description,
            seats_limited: dto.seats_limited,
            seats_max: dto.seats_max,
            default_date_tz: dto.default_date_tz,
            is_multi_slots: dto.is_multi_slots,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EventType> for EventTypeResponseDto {
    fn from(entity: &EventType) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            description: entity.description.clone(),
            seats_limited: entity.seats_limited.clone(),
            seats_max: entity.seats_max.clone(),
            default_date_tz: entity.default_date_tz.clone(),
            is_multi_slots: entity.is_multi_slots.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEventTypeDto> for EventType {
    fn from_create_dto(dto: CreateEventTypeDto) -> backbone_core::ServiceResult<Self> {
        Ok(EventType::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEventTypeDto> for EventType {
    fn apply_update(mut self, dto: UpdateEventTypeDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.description = dto.description;
        self.seats_limited = dto.seats_limited;
        self.seats_max = dto.seats_max;
        self.default_date_tz = dto.default_date_tz;
        self.is_multi_slots = dto.is_multi_slots;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EventType here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
