//! LeadRequest DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::LeadRequest;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new LeadRequest
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateLeadRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub done: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "claimed_at")]
    pub claimed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a LeadRequest
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateLeadRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub done: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "claimed_at")]
    pub claimed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a LeadRequest
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchLeadRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub done: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "claimed_at")]
    pub claimed_at: Option<DateTime<Utc>>,
}

impl PatchLeadRequestDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.event_id.is_some() || self.done.is_some() || self.error_detail.is_some() || self.claimed_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for LeadRequest entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeadRequestResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub done: bool,
    pub error_detail: Option<String>,
    pub claimed_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for LeadRequest entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeadRequestListResponseDto {
    /// List of items
    pub items: Vec<LeadRequestResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl LeadRequestListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<LeadRequestResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeadRequestSummaryDto {
    pub id: Uuid,
    pub event_id: Uuid,
    pub done: bool,
    pub error_detail: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<LeadRequest> for LeadRequestResponseDto {
    fn from(entity: LeadRequest) -> Self {
        Self {
            id: entity.id,
            event_id: entity.event_id,
            done: entity.done,
            error_detail: entity.error_detail,
            claimed_at: entity.claimed_at,
            metadata: entity.metadata,
        }
    }
}

impl From<LeadRequest> for LeadRequestSummaryDto {
    fn from(entity: LeadRequest) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            event_id: entity.event_id,
            done: entity.done,
            error_detail: entity.error_detail,
            created_at,
        }
    }
}

impl From<CreateLeadRequestDto> for LeadRequest {
    fn from(dto: CreateLeadRequestDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            event_id: dto.event_id,
            done: dto.done,
            error_detail: dto.error_detail,
            claimed_at: dto.claimed_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&LeadRequest> for LeadRequestResponseDto {
    fn from(entity: &LeadRequest) -> Self {
        Self {
            id: entity.id.clone(),
            event_id: entity.event_id.clone(),
            done: entity.done.clone(),
            error_detail: entity.error_detail.clone(),
            claimed_at: entity.claimed_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateLeadRequestDto> for LeadRequest {
    fn from_create_dto(dto: CreateLeadRequestDto) -> backbone_core::ServiceResult<Self> {
        Ok(LeadRequest::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateLeadRequestDto> for LeadRequest {
    fn apply_update(mut self, dto: UpdateLeadRequestDto) -> backbone_core::ServiceResult<Self> {
        self.event_id = dto.event_id;
        self.done = dto.done;
        self.error_detail = dto.error_detail;
        self.claimed_at = dto.claimed_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to LeadRequest here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
