//! LeadRule DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::LeadRule;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EventLeadBasis;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new LeadRule
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateLeadRuleDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    pub basis: EventLeadBasis,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "on_create")]
    pub on_create: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "on_confirm")]
    pub on_confirm: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "on_done")]
    pub on_done: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a LeadRule
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateLeadRuleDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    pub basis: EventLeadBasis,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "on_create")]
    pub on_create: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "on_confirm")]
    pub on_confirm: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "on_done")]
    pub on_done: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a LeadRule
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchLeadRuleDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub basis: Option<EventLeadBasis>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "on_create")]
    pub on_create: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "on_confirm")]
    pub on_confirm: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "on_done")]
    pub on_done: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl PatchLeadRuleDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.event_id.is_some() || self.basis.is_some() || self.on_create.is_some() || self.on_confirm.is_some() || self.on_done.is_some() || self.active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for LeadRule entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeadRuleResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub event_id: Option<Uuid>,
    pub basis: EventLeadBasis,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub on_create: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub on_confirm: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub on_done: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for LeadRule entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeadRuleListResponseDto {
    /// List of items
    pub items: Vec<LeadRuleResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl LeadRuleListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<LeadRuleResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeadRuleSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub event_id: Option<Uuid>,
    pub basis: EventLeadBasis,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<LeadRule> for LeadRuleResponseDto {
    fn from(entity: LeadRule) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            event_id: entity.event_id,
            basis: entity.basis,
            on_create: entity.on_create,
            on_confirm: entity.on_confirm,
            on_done: entity.on_done,
            active: entity.active,
            metadata: entity.metadata,
        }
    }
}

impl From<LeadRule> for LeadRuleSummaryDto {
    fn from(entity: LeadRule) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            event_id: entity.event_id,
            basis: entity.basis,
            created_at,
        }
    }
}

impl From<CreateLeadRuleDto> for LeadRule {
    fn from(dto: CreateLeadRuleDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            event_id: dto.event_id,
            basis: dto.basis,
            on_create: dto.on_create,
            on_confirm: dto.on_confirm,
            on_done: dto.on_done,
            active: dto.active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&LeadRule> for LeadRuleResponseDto {
    fn from(entity: &LeadRule) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            event_id: entity.event_id.clone(),
            basis: entity.basis.clone(),
            on_create: entity.on_create.clone(),
            on_confirm: entity.on_confirm.clone(),
            on_done: entity.on_done.clone(),
            active: entity.active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateLeadRuleDto> for LeadRule {
    fn from_create_dto(dto: CreateLeadRuleDto) -> backbone_core::ServiceResult<Self> {
        Ok(LeadRule::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateLeadRuleDto> for LeadRule {
    fn apply_update(mut self, dto: UpdateLeadRuleDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.event_id = dto.event_id;
        self.basis = dto.basis;
        self.on_create = dto.on_create;
        self.on_confirm = dto.on_confirm;
        self.on_done = dto.on_done;
        self.active = dto.active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to LeadRule here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
