//! MailRegistration DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailRegistration;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailRegistration
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailRegistrationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "scheduler_id")]
    pub scheduler_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "registration_id")]
    pub registration_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scheduled_date")]
    pub scheduled_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "mail_sent")]
    pub mail_sent: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outcome: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailRegistration
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailRegistrationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "scheduler_id")]
    pub scheduler_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "registration_id")]
    pub registration_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scheduled_date")]
    pub scheduled_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "mail_sent")]
    pub mail_sent: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outcome: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailRegistration
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailRegistrationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "scheduler_id")]
    pub scheduler_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "registration_id")]
    pub registration_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "scheduled_date")]
    pub scheduled_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "mail_sent")]
    pub mail_sent: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outcome: Option<String>,
}

impl PatchMailRegistrationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.scheduler_id.is_some() || self.registration_id.is_some() || self.scheduled_date.is_some() || self.mail_sent.is_some() || self.outcome.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailRegistration entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailRegistrationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub scheduler_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub registration_id: Uuid,
    pub scheduled_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub mail_sent: bool,
    pub outcome: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailRegistration entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailRegistrationListResponseDto {
    /// List of items
    pub items: Vec<MailRegistrationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailRegistrationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailRegistrationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailRegistrationSummaryDto {
    pub id: Uuid,
    pub scheduler_id: Uuid,
    pub registration_id: Uuid,
    pub scheduled_date: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailRegistration> for MailRegistrationResponseDto {
    fn from(entity: MailRegistration) -> Self {
        Self {
            id: entity.id,
            scheduler_id: entity.scheduler_id,
            registration_id: entity.registration_id,
            scheduled_date: entity.scheduled_date,
            mail_sent: entity.mail_sent,
            outcome: entity.outcome,
            metadata: entity.metadata,
        }
    }
}

impl From<MailRegistration> for MailRegistrationSummaryDto {
    fn from(entity: MailRegistration) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            scheduler_id: entity.scheduler_id,
            registration_id: entity.registration_id,
            scheduled_date: entity.scheduled_date,
            created_at,
        }
    }
}

impl From<CreateMailRegistrationDto> for MailRegistration {
    fn from(dto: CreateMailRegistrationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            scheduler_id: dto.scheduler_id,
            registration_id: dto.registration_id,
            scheduled_date: dto.scheduled_date,
            mail_sent: dto.mail_sent,
            outcome: dto.outcome,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailRegistration> for MailRegistrationResponseDto {
    fn from(entity: &MailRegistration) -> Self {
        Self {
            id: entity.id.clone(),
            scheduler_id: entity.scheduler_id.clone(),
            registration_id: entity.registration_id.clone(),
            scheduled_date: entity.scheduled_date.clone(),
            mail_sent: entity.mail_sent.clone(),
            outcome: entity.outcome.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailRegistrationDto> for MailRegistration {
    fn from_create_dto(dto: CreateMailRegistrationDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailRegistration::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailRegistrationDto> for MailRegistration {
    fn apply_update(mut self, dto: UpdateMailRegistrationDto) -> backbone_core::ServiceResult<Self> {
        self.scheduler_id = dto.scheduler_id;
        self.registration_id = dto.registration_id;
        self.scheduled_date = dto.scheduled_date;
        self.mail_sent = dto.mail_sent;
        self.outcome = dto.outcome;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailRegistration here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
