//! RegistrationQuestion DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::RegistrationQuestion;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new RegistrationQuestion
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateRegistrationQuestionDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "event_type_id")]
    pub event_type_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "question_id")]
    pub question_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a RegistrationQuestion
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateRegistrationQuestionDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "event_type_id")]
    pub event_type_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "question_id")]
    pub question_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a RegistrationQuestion
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchRegistrationQuestionDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_type_id")]
    pub event_type_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "question_id")]
    pub question_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
}

impl PatchRegistrationQuestionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.event_id.is_some() || self.event_type_id.is_some() || self.question_id.is_some() || self.sequence.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for RegistrationQuestion entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RegistrationQuestionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub event_id: Option<Uuid>,
    pub event_type_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub question_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for RegistrationQuestion entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RegistrationQuestionListResponseDto {
    /// List of items
    pub items: Vec<RegistrationQuestionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl RegistrationQuestionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<RegistrationQuestionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RegistrationQuestionSummaryDto {
    pub id: Uuid,
    pub event_id: Option<Uuid>,
    pub event_type_id: Option<Uuid>,
    pub question_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<RegistrationQuestion> for RegistrationQuestionResponseDto {
    fn from(entity: RegistrationQuestion) -> Self {
        Self {
            id: entity.id,
            event_id: entity.event_id,
            event_type_id: entity.event_type_id,
            question_id: entity.question_id,
            sequence: entity.sequence,
            metadata: entity.metadata,
        }
    }
}

impl From<RegistrationQuestion> for RegistrationQuestionSummaryDto {
    fn from(entity: RegistrationQuestion) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            event_id: entity.event_id,
            event_type_id: entity.event_type_id,
            question_id: entity.question_id,
            created_at,
        }
    }
}

impl From<CreateRegistrationQuestionDto> for RegistrationQuestion {
    fn from(dto: CreateRegistrationQuestionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            event_id: dto.event_id,
            event_type_id: dto.event_type_id,
            question_id: dto.question_id,
            sequence: dto.sequence,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&RegistrationQuestion> for RegistrationQuestionResponseDto {
    fn from(entity: &RegistrationQuestion) -> Self {
        Self {
            id: entity.id.clone(),
            event_id: entity.event_id.clone(),
            event_type_id: entity.event_type_id.clone(),
            question_id: entity.question_id.clone(),
            sequence: entity.sequence.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateRegistrationQuestionDto> for RegistrationQuestion {
    fn from_create_dto(dto: CreateRegistrationQuestionDto) -> backbone_core::ServiceResult<Self> {
        Ok(RegistrationQuestion::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateRegistrationQuestionDto> for RegistrationQuestion {
    fn apply_update(mut self, dto: UpdateRegistrationQuestionDto) -> backbone_core::ServiceResult<Self> {
        self.event_id = dto.event_id;
        self.event_type_id = dto.event_type_id;
        self.question_id = dto.question_id;
        self.sequence = dto.sequence;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to RegistrationQuestion here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
