//! Stage DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Stage;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Stage
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateStageDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub fold: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "pipe_end")]
    pub pipe_end: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Stage
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateStageDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub fold: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "pipe_end")]
    pub pipe_end: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Stage
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchStageDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fold: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "pipe_end")]
    pub pipe_end: Option<bool>,
}

impl PatchStageDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.sequence.is_some() || self.fold.is_some() || self.pipe_end.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Stage entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StageResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub fold: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub pipe_end: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Stage entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StageListResponseDto {
    /// List of items
    pub items: Vec<StageResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl StageListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<StageResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StageSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub sequence: i32,
    pub fold: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Stage> for StageResponseDto {
    fn from(entity: Stage) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            sequence: entity.sequence,
            fold: entity.fold,
            pipe_end: entity.pipe_end,
            metadata: entity.metadata,
        }
    }
}

impl From<Stage> for StageSummaryDto {
    fn from(entity: Stage) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            sequence: entity.sequence,
            fold: entity.fold,
            created_at,
        }
    }
}

impl From<CreateStageDto> for Stage {
    fn from(dto: CreateStageDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            sequence: dto.sequence,
            fold: dto.fold,
            pipe_end: dto.pipe_end,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Stage> for StageResponseDto {
    fn from(entity: &Stage) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            sequence: entity.sequence.clone(),
            fold: entity.fold.clone(),
            pipe_end: entity.pipe_end.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateStageDto> for Stage {
    fn from_create_dto(dto: CreateStageDto) -> backbone_core::ServiceResult<Self> {
        Ok(Stage::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateStageDto> for Stage {
    fn apply_update(mut self, dto: UpdateStageDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.sequence = dto.sequence;
        self.fold = dto.fold;
        self.pipe_end = dto.pipe_end;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Stage here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
