//! Tag DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Tag;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Tag
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTagDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "category_id")]
    pub category_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 32)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Tag
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTagDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "category_id")]
    pub category_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 32)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Tag
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTagDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "category_id")]
    pub category_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 32)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
}

impl PatchTagDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.category_id.is_some() || self.color.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Tag entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TagResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub category_id: Option<Uuid>,
    pub color: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Tag entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TagListResponseDto {
    /// List of items
    pub items: Vec<TagResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TagListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TagResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TagSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub category_id: Option<Uuid>,
    pub color: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Tag> for TagResponseDto {
    fn from(entity: Tag) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            category_id: entity.category_id,
            color: entity.color,
            metadata: entity.metadata,
        }
    }
}

impl From<Tag> for TagSummaryDto {
    fn from(entity: Tag) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            category_id: entity.category_id,
            color: entity.color,
            created_at,
        }
    }
}

impl From<CreateTagDto> for Tag {
    fn from(dto: CreateTagDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            category_id: dto.category_id,
            color: dto.color,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Tag> for TagResponseDto {
    fn from(entity: &Tag) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            category_id: entity.category_id.clone(),
            color: entity.color.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTagDto> for Tag {
    fn from_create_dto(dto: CreateTagDto) -> backbone_core::ServiceResult<Self> {
        Ok(Tag::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTagDto> for Tag {
    fn apply_update(mut self, dto: UpdateTagDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.category_id = dto.category_id;
        self.color = dto.color;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Tag here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
