//! Ticket DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Ticket;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Ticket
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTicketDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "seats_max")]
    pub seats_max: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "seats_max_per_order")]
    pub seats_max_per_order: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "start_sale_datetime")]
    pub start_sale_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_sale_datetime")]
    pub end_sale_datetime: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Ticket
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTicketDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "seats_max")]
    pub seats_max: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "seats_max_per_order")]
    pub seats_max_per_order: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "start_sale_datetime")]
    pub start_sale_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_sale_datetime")]
    pub end_sale_datetime: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Ticket
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTicketDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "seats_max")]
    pub seats_max: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "seats_max_per_order")]
    pub seats_max_per_order: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "start_sale_datetime")]
    pub start_sale_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "end_sale_datetime")]
    pub end_sale_datetime: Option<DateTime<Utc>>,
}

impl PatchTicketDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.event_id.is_some() || self.name.is_some() || self.seats_max.is_some() || self.seats_max_per_order.is_some() || self.start_sale_datetime.is_some() || self.end_sale_datetime.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Ticket entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TicketResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub seats_max: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub seats_max_per_order: i32,
    pub start_sale_datetime: Option<DateTime<Utc>>,
    pub end_sale_datetime: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Ticket entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TicketListResponseDto {
    /// List of items
    pub items: Vec<TicketResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TicketListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TicketResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TicketSummaryDto {
    pub id: Uuid,
    pub event_id: Uuid,
    pub name: String,
    pub seats_max: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Ticket> for TicketResponseDto {
    fn from(entity: Ticket) -> Self {
        Self {
            id: entity.id,
            event_id: entity.event_id,
            name: entity.name,
            seats_max: entity.seats_max,
            seats_max_per_order: entity.seats_max_per_order,
            start_sale_datetime: entity.start_sale_datetime,
            end_sale_datetime: entity.end_sale_datetime,
            metadata: entity.metadata,
        }
    }
}

impl From<Ticket> for TicketSummaryDto {
    fn from(entity: Ticket) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            event_id: entity.event_id,
            name: entity.name,
            seats_max: entity.seats_max,
            created_at,
        }
    }
}

impl From<CreateTicketDto> for Ticket {
    fn from(dto: CreateTicketDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            event_id: dto.event_id,
            name: dto.name,
            seats_max: dto.seats_max,
            seats_max_per_order: dto.seats_max_per_order,
            start_sale_datetime: dto.start_sale_datetime,
            end_sale_datetime: dto.end_sale_datetime,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Ticket> for TicketResponseDto {
    fn from(entity: &Ticket) -> Self {
        Self {
            id: entity.id.clone(),
            event_id: entity.event_id.clone(),
            name: entity.name.clone(),
            seats_max: entity.seats_max.clone(),
            seats_max_per_order: entity.seats_max_per_order.clone(),
            start_sale_datetime: entity.start_sale_datetime.clone(),
            end_sale_datetime: entity.end_sale_datetime.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTicketDto> for Ticket {
    fn from_create_dto(dto: CreateTicketDto) -> backbone_core::ServiceResult<Self> {
        Ok(Ticket::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTicketDto> for Ticket {
    fn apply_update(mut self, dto: UpdateTicketDto) -> backbone_core::ServiceResult<Self> {
        self.event_id = dto.event_id;
        self.name = dto.name;
        self.seats_max = dto.seats_max;
        self.seats_max_per_order = dto.seats_max_per_order;
        self.start_sale_datetime = dto.start_sale_datetime;
        self.end_sale_datetime = dto.end_sale_datetime;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Ticket here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
