//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod event_specification;
pub mod event_audit_log_specification;
pub mod event_type_specification;
pub mod mail_specification;
pub mod mail_registration_specification;
pub mod mail_slot_specification;
pub mod question_specification;
pub mod question_answer_specification;
pub mod registration_question_specification;
pub mod registration_specification;
pub mod registration_answer_specification;
pub mod slot_specification;
pub mod stage_specification;
pub mod tag_category_specification;
pub mod tag_specification;
pub mod ticket_specification;
pub mod type_mail_specification;

// <<< CUSTOM
// END CUSTOM
