//! Application service for BoothBooking entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `booth_booking_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBoothBookingDto, UpdateBoothBookingDto};
use crate::domain::entity::BoothBooking;
use crate::infrastructure::persistence::BoothBookingRepository;

/// Application service for BoothBooking entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `booth_booking_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BoothBookingServiceCustom {
///     inner: Arc<BoothBookingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BoothBookingService = GenericCrudService<
    BoothBooking,
    CreateBoothBookingDto,
    UpdateBoothBookingDto,
    BoothBookingRepository,
>;

// <<< CUSTOM
// END CUSTOM
