//! Application service for EventType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `event_type_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEventTypeDto, UpdateEventTypeDto};
use crate::domain::entity::EventType;
use crate::infrastructure::persistence::EventTypeRepository;

/// Application service for EventType entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `event_type_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EventTypeServiceCustom {
///     inner: Arc<EventTypeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EventTypeService = GenericCrudService<
    EventType,
    CreateEventTypeDto,
    UpdateEventTypeDto,
    EventTypeRepository,
>;

// <<< CUSTOM
// END CUSTOM
