//! Application service for LeadProvenanceRegistration entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `lead_provenance_registration_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateLeadProvenanceRegistrationDto, UpdateLeadProvenanceRegistrationDto};
use crate::domain::entity::LeadProvenanceRegistration;
use crate::infrastructure::persistence::LeadProvenanceRegistrationRepository;

/// Application service for LeadProvenanceRegistration entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `lead_provenance_registration_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct LeadProvenanceRegistrationServiceCustom {
///     inner: Arc<LeadProvenanceRegistrationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type LeadProvenanceRegistrationService = GenericCrudService<
    LeadProvenanceRegistration,
    CreateLeadProvenanceRegistrationDto,
    UpdateLeadProvenanceRegistrationDto,
    LeadProvenanceRegistrationRepository,
>;

// <<< CUSTOM
// END CUSTOM
