//! Application service for LeadRule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `lead_rule_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateLeadRuleDto, UpdateLeadRuleDto};
use crate::domain::entity::LeadRule;
use crate::infrastructure::persistence::LeadRuleRepository;

/// Application service for LeadRule entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `lead_rule_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct LeadRuleServiceCustom {
///     inner: Arc<LeadRuleService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type LeadRuleService = GenericCrudService<
    LeadRule,
    CreateLeadRuleDto,
    UpdateLeadRuleDto,
    LeadRuleRepository,
>;

// <<< CUSTOM
// END CUSTOM
