//! Application service for MailRegistration entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mail_registration_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailRegistrationDto, UpdateMailRegistrationDto};
use crate::domain::entity::MailRegistration;
use crate::infrastructure::persistence::MailRegistrationRepository;

/// Application service for MailRegistration entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mail_registration_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailRegistrationServiceCustom {
///     inner: Arc<MailRegistrationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailRegistrationService = GenericCrudService<
    MailRegistration,
    CreateMailRegistrationDto,
    UpdateMailRegistrationDto,
    MailRegistrationRepository,
>;

// <<< CUSTOM
// END CUSTOM
