//! Application service for Stage entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `stage_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateStageDto, UpdateStageDto};
use crate::domain::entity::Stage;
use crate::infrastructure::persistence::StageRepository;

/// Application service for Stage entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `stage_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct StageServiceCustom {
///     inner: Arc<StageService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type StageService = GenericCrudService<
    Stage,
    CreateStageDto,
    UpdateStageDto,
    StageRepository,
>;

// <<< CUSTOM
// END CUSTOM
