//! Application service for Ticket entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `ticket_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTicketDto, UpdateTicketDto};
use crate::domain::entity::Ticket;
use crate::infrastructure::persistence::TicketRepository;

/// Application service for Ticket entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `ticket_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TicketServiceCustom {
///     inner: Arc<TicketService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TicketService = GenericCrudService<
    Ticket,
    CreateTicketDto,
    UpdateTicketDto,
    TicketRepository,
>;

// <<< CUSTOM
// END CUSTOM
