//! Application service for TypeMail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `type_mail_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTypeMailDto, UpdateTypeMailDto};
use crate::domain::entity::TypeMail;
use crate::infrastructure::persistence::TypeMailRepository;

/// Application service for TypeMail entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `type_mail_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TypeMailServiceCustom {
///     inner: Arc<TypeMailService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TypeMailService = GenericCrudService<
    TypeMail,
    CreateTypeMailDto,
    UpdateTypeMailDto,
    TypeMailRepository,
>;

// <<< CUSTOM
// END CUSTOM
