-- BoothBooking Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the event.booth_bookings table.
-- Customize this file to add your initial data.

-- INSERT INTO event.booth_bookings (
--     id,
--     event_booth_id,
--     sale_order_line_id,
--     status,
--     partner_id,
--     contact_name,
--     contact_email,
--     contact_phone,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO event.booth_bookings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

