-- LeadRulePredicate Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the event.lead_rule_predicates table.
-- Customize this file to add your initial data.

-- INSERT INTO event.lead_rule_predicates (
--     id,
--     rule_id,
--     axis,
--     question_id,
--     value_ids,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO event.lead_rule_predicates (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

