-- MailRegistration Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the event.mail_registrations table.
-- Customize this file to add your initial data.

-- INSERT INTO event.mail_registrations (
--     id,
--     scheduler_id,
--     registration_id,
--     scheduled_date,
--     mail_sent,
--     outcome,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO event.mail_registrations (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

