-- TypeMail Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the event.type_mails table.
-- Customize this file to add your initial data.

-- INSERT INTO event.type_mails (
--     id,
--     event_type_id,
--     interval_nbr,
--     interval_unit,
--     interval_kind,
--     notification_channel,
--     template_ref,
--     template_kind,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO event.type_mails (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

