-- Migration: Create slots table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.slots (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL,
    name TEXT NOT NULL,
    date_begin TIMESTAMPTZ NOT NULL,
    date_end TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_slots_event_id_date_begin ON event.slots (event_id, date_begin);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_slots_metadata_gin ON event.slots USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_slots_metadata_deleted_at ON event.slots ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_slots_metadata_created_at ON event.slots ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_slots_metadata_updated_at ON event.slots ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.slots_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS slots_insert_audit ON event.slots;
CREATE TRIGGER slots_insert_audit BEFORE INSERT ON event.slots
    FOR EACH ROW EXECUTE FUNCTION event.slots_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS slots_update_audit ON event.slots;
CREATE TRIGGER slots_update_audit BEFORE UPDATE ON event.slots
    FOR EACH ROW EXECUTE FUNCTION event.slots_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE event.slots ADD CONSTRAINT fk_slots_event_id FOREIGN KEY (event_id) REFERENCES event.events (id);
