-- Migration: Create booth_bookings table
-- Generated by metaphor-schema

-- Create event_booth_booking_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_booth_booking_status') THEN
        CREATE TYPE event_booth_booking_status AS ENUM ('pending', 'confirmed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.booth_bookings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    event_booth_id UUID NOT NULL,
    sale_order_line_id UUID,
    status event_booth_booking_status NOT NULL DEFAULT 'pending',
    partner_id UUID,
    contact_name TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_booth_bookings_event_booth_id_status ON event.booth_bookings (event_booth_id, status);

CREATE INDEX IF NOT EXISTS idx_booth_bookings_sale_order_line_id ON event.booth_bookings (sale_order_line_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_booth_bookings_metadata_gin ON event.booth_bookings USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_booth_bookings_metadata_deleted_at ON event.booth_bookings ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_booth_bookings_metadata_created_at ON event.booth_bookings ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_booth_bookings_metadata_updated_at ON event.booth_bookings ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.booth_bookings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS booth_bookings_insert_audit ON event.booth_bookings;
CREATE TRIGGER booth_bookings_insert_audit BEFORE INSERT ON event.booth_bookings
    FOR EACH ROW EXECUTE FUNCTION event.booth_bookings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS booth_bookings_update_audit ON event.booth_bookings;
CREATE TRIGGER booth_bookings_update_audit BEFORE UPDATE ON event.booth_bookings
    FOR EACH ROW EXECUTE FUNCTION event.booth_bookings_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
-- NOTE (generator defect, frozen user-owned): the emitted FK to
-- event.booths references a table this file ordering creates LATER
-- (20260426220033_create_booth_table). The constraint moves to the
-- overlay hardening migration (20260426220040), which runs after every
-- overlay table exists — same freeze pattern as 20005/20017.
