-- Migration: Create registrations table
-- Generated by metaphor-schema

-- Create event_registration_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_registration_state') THEN
        CREATE TYPE event_registration_state AS ENUM ('draft', 'open', 'done', 'cancel');
    END IF;
END
$$;

-- Create event_sale_order_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_sale_order_state') THEN
        CREATE TYPE event_sale_order_state AS ENUM ('draft', 'sent', 'sale', 'cancel');
    END IF;
END
$$;

-- Create event_sale_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_sale_status') THEN
        CREATE TYPE event_sale_status AS ENUM ('free', 'sold', 'to_pay');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.registrations (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL,
    event_slot_id UUID,
    event_ticket_id UUID,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    company_name TEXT,
    partner_id UUID,
    state event_registration_state NOT NULL DEFAULT 'open',
    date_closed TIMESTAMPTZ,
    sale_order_id UUID,
    sale_order_state event_sale_order_state,
    sale_status event_sale_status,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    barcode TEXT NOT NULL,
    company_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_registrations_event_id_state_active ON event.registrations (event_id, state, active);

CREATE INDEX IF NOT EXISTS idx_registrations_sale_order_id ON event.registrations (sale_order_id);

CREATE INDEX IF NOT EXISTS idx_registrations_email ON event.registrations (email);

CREATE UNIQUE INDEX IF NOT EXISTS idx_registrations_barcode ON event.registrations (barcode);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_registrations_metadata_gin ON event.registrations USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_registrations_metadata_deleted_at ON event.registrations ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_registrations_metadata_created_at ON event.registrations ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_registrations_metadata_updated_at ON event.registrations ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.registrations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS registrations_insert_audit ON event.registrations;
CREATE TRIGGER registrations_insert_audit BEFORE INSERT ON event.registrations
    FOR EACH ROW EXECUTE FUNCTION event.registrations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS registrations_update_audit ON event.registrations;
CREATE TRIGGER registrations_update_audit BEFORE UPDATE ON event.registrations
    FOR EACH ROW EXECUTE FUNCTION event.registrations_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE event.registrations ADD CONSTRAINT fk_registrations_event_id FOREIGN KEY (event_id) REFERENCES event.events (id);
ALTER TABLE event.registrations ADD CONSTRAINT fk_registrations_event_slot_id FOREIGN KEY (event_slot_id) REFERENCES event.slots (id);
ALTER TABLE event.registrations ADD CONSTRAINT fk_registrations_event_ticket_id FOREIGN KEY (event_ticket_id) REFERENCES event.tickets (id);
