-- Migration: Create lead_provenances table
-- Generated by metaphor-schema

-- Create event_lead_grouping enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_lead_grouping') THEN
        CREATE TYPE event_lead_grouping AS ENUM ('per_order', 'per_event_day');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.lead_provenances (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    rule_id UUID NOT NULL,
    event_id UUID NOT NULL,
    lead_id UUID,
    group_key TEXT NOT NULL,
    grouping event_lead_grouping NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_lead_provenances_rule_id_group_key ON event.lead_provenances (rule_id, group_key);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_lead_provenances_metadata_gin ON event.lead_provenances USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_lead_provenances_metadata_deleted_at ON event.lead_provenances ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_lead_provenances_metadata_created_at ON event.lead_provenances ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_lead_provenances_metadata_updated_at ON event.lead_provenances ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.lead_provenances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS lead_provenances_insert_audit ON event.lead_provenances;
CREATE TRIGGER lead_provenances_insert_audit BEFORE INSERT ON event.lead_provenances
    FOR EACH ROW EXECUTE FUNCTION event.lead_provenances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS lead_provenances_update_audit ON event.lead_provenances;
CREATE TRIGGER lead_provenances_update_audit BEFORE UPDATE ON event.lead_provenances
    FOR EACH ROW EXECUTE FUNCTION event.lead_provenances_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
-- NOTE (generator defect, frozen user-owned): the FK to
-- event.lead_rules references a table this file ordering creates
-- LATER (20260426220038). The constraint moves to the overlay
-- hardening migration (20260426220040).
ALTER TABLE event.lead_provenances ADD CONSTRAINT fk_lead_provenances_event_id FOREIGN KEY (event_id) REFERENCES event.events (id);
