-- Migration: Create booth_categories table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.booth_categories (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    product_id UUID,
    price NUMERIC,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_booth_categories_name ON event.booth_categories (name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_booth_categories_metadata_gin ON event.booth_categories USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_booth_categories_metadata_deleted_at ON event.booth_categories ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_booth_categories_metadata_created_at ON event.booth_categories ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_booth_categories_metadata_updated_at ON event.booth_categories ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.booth_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS booth_categories_insert_audit ON event.booth_categories;
CREATE TRIGGER booth_categories_insert_audit BEFORE INSERT ON event.booth_categories
    FOR EACH ROW EXECUTE FUNCTION event.booth_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS booth_categories_update_audit ON event.booth_categories;
CREATE TRIGGER booth_categories_update_audit BEFORE UPDATE ON event.booth_categories
    FOR EACH ROW EXECUTE FUNCTION event.booth_categories_audit_timestamp();
