-- Enum types for event module
-- Generated by metaphor-schema

-- Create event_kanban_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_kanban_state') THEN
        CREATE TYPE event_kanban_state AS ENUM ('normal', 'done', 'blocked', 'cancel');
    END IF;
END
$$;

-- Create event_badge_format enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_badge_format') THEN
        CREATE TYPE event_badge_format AS ENUM ('a4_french_fold', 'a6', 'four_per_sheet');
    END IF;
END
$$;

-- Create event_audit_event enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_audit_event') THEN
        CREATE TYPE event_audit_event AS ENUM ('event_created', 'event_updated', 'event_published', 'event_unpublished', 'publish_refused', 'event_mark_done', 'registration_created', 'registration_refused', 'registration_state_changed', 'registration_archived', 'scheduler_created', 'scheduler_run', 'scheduler_failed', 'receipt_dropped_window_closed', 'capability_refused');
    END IF;
END
$$;

-- Create event_interval_unit enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_interval_unit') THEN
        CREATE TYPE event_interval_unit AS ENUM ('now', 'hours', 'days', 'weeks', 'months');
    END IF;
END
$$;

-- Create event_interval_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_interval_kind') THEN
        CREATE TYPE event_interval_kind AS ENUM ('after_sub', 'before_event', 'after_event_start', 'after_event', 'before_event_end');
    END IF;
END
$$;

-- Create event_notification_channel enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_notification_channel') THEN
        CREATE TYPE event_notification_channel AS ENUM ('mail');
    END IF;
END
$$;

-- Create event_mail_error_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_mail_error_kind') THEN
        CREATE TYPE event_mail_error_kind AS ENUM ('template_unresolved', 'template_renderer_not_composed', 'render_failed', 'enqueue_refused', 'recipient_invalid');
    END IF;
END
$$;

-- Create event_question_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_question_kind') THEN
        CREATE TYPE event_question_kind AS ENUM ('text_box', 'simple_choice', 'name', 'email', 'phone', 'company_name');
    END IF;
END
$$;

-- Create event_registration_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_registration_state') THEN
        CREATE TYPE event_registration_state AS ENUM ('draft', 'open', 'done', 'cancel');
    END IF;
END
$$;

-- Create event_sale_order_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_sale_order_state') THEN
        CREATE TYPE event_sale_order_state AS ENUM ('draft', 'sent', 'sale', 'cancel');
    END IF;
END
$$;

-- Create event_sale_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_sale_status') THEN
        CREATE TYPE event_sale_status AS ENUM ('free', 'sold', 'to_pay');
    END IF;
END
$$;

