-- Migration: Create mail_registrations table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.mail_registrations (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    scheduler_id UUID NOT NULL,
    registration_id UUID NOT NULL,
    scheduled_date TIMESTAMPTZ,
    mail_sent BOOLEAN NOT NULL DEFAULT FALSE,
    outcome TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mail_registrations_scheduler_id_registration_id ON event.mail_registrations (scheduler_id, registration_id);

CREATE INDEX IF NOT EXISTS idx_mail_registrations_scheduled_date_mail_sent ON event.mail_registrations (scheduled_date, mail_sent);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mail_registrations_metadata_gin ON event.mail_registrations USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mail_registrations_metadata_deleted_at ON event.mail_registrations ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mail_registrations_metadata_created_at ON event.mail_registrations ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mail_registrations_metadata_updated_at ON event.mail_registrations ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.mail_registrations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_registrations_insert_audit ON event.mail_registrations;
CREATE TRIGGER mail_registrations_insert_audit BEFORE INSERT ON event.mail_registrations
    FOR EACH ROW EXECUTE FUNCTION event.mail_registrations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_registrations_update_audit ON event.mail_registrations;
CREATE TRIGGER mail_registrations_update_audit BEFORE UPDATE ON event.mail_registrations
    FOR EACH ROW EXECUTE FUNCTION event.mail_registrations_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE event.mail_registrations ADD CONSTRAINT fk_mail_registrations_scheduler_id FOREIGN KEY (scheduler_id) REFERENCES event.mails (id);
ALTER TABLE event.mail_registrations ADD CONSTRAINT fk_mail_registrations_registration_id FOREIGN KEY (registration_id) REFERENCES event.registrations (id);
