-- Company RLS fence for event module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for event.events
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE event.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE event.events FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS events_company_isolation ON event.events;
CREATE POLICY events_company_isolation ON event.events
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL);

-- Migration: company row-level-security fence for event.registrations
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE event.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE event.registrations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS registrations_company_isolation ON event.registrations;
CREATE POLICY registrations_company_isolation ON event.registrations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL);

