-- Audit Triggers Migration for event module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Event (event.events)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.events_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS events_insert_audit ON event.events;
CREATE TRIGGER events_insert_audit BEFORE INSERT ON event.events
    FOR EACH ROW EXECUTE FUNCTION event.events_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS events_update_audit ON event.events;
CREATE TRIGGER events_update_audit BEFORE UPDATE ON event.events
    FOR EACH ROW EXECUTE FUNCTION event.events_audit_timestamp();

-- ==============================================================================
-- Table: EventType (event.types)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.types_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS types_insert_audit ON event.types;
CREATE TRIGGER types_insert_audit BEFORE INSERT ON event.types
    FOR EACH ROW EXECUTE FUNCTION event.types_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS types_update_audit ON event.types;
CREATE TRIGGER types_update_audit BEFORE UPDATE ON event.types
    FOR EACH ROW EXECUTE FUNCTION event.types_audit_timestamp();

-- ==============================================================================
-- Table: Mail (event.mails)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.mails_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mails_insert_audit ON event.mails;
CREATE TRIGGER mails_insert_audit BEFORE INSERT ON event.mails
    FOR EACH ROW EXECUTE FUNCTION event.mails_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mails_update_audit ON event.mails;
CREATE TRIGGER mails_update_audit BEFORE UPDATE ON event.mails
    FOR EACH ROW EXECUTE FUNCTION event.mails_audit_timestamp();

-- ==============================================================================
-- Table: MailRegistration (event.mail_registrations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.mail_registrations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_registrations_insert_audit ON event.mail_registrations;
CREATE TRIGGER mail_registrations_insert_audit BEFORE INSERT ON event.mail_registrations
    FOR EACH ROW EXECUTE FUNCTION event.mail_registrations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_registrations_update_audit ON event.mail_registrations;
CREATE TRIGGER mail_registrations_update_audit BEFORE UPDATE ON event.mail_registrations
    FOR EACH ROW EXECUTE FUNCTION event.mail_registrations_audit_timestamp();

-- ==============================================================================
-- Table: MailSlot (event.mail_slots)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.mail_slots_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_slots_insert_audit ON event.mail_slots;
CREATE TRIGGER mail_slots_insert_audit BEFORE INSERT ON event.mail_slots
    FOR EACH ROW EXECUTE FUNCTION event.mail_slots_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_slots_update_audit ON event.mail_slots;
CREATE TRIGGER mail_slots_update_audit BEFORE UPDATE ON event.mail_slots
    FOR EACH ROW EXECUTE FUNCTION event.mail_slots_audit_timestamp();

-- ==============================================================================
-- Table: Question (event.questions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.questions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS questions_insert_audit ON event.questions;
CREATE TRIGGER questions_insert_audit BEFORE INSERT ON event.questions
    FOR EACH ROW EXECUTE FUNCTION event.questions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS questions_update_audit ON event.questions;
CREATE TRIGGER questions_update_audit BEFORE UPDATE ON event.questions
    FOR EACH ROW EXECUTE FUNCTION event.questions_audit_timestamp();

-- ==============================================================================
-- Table: QuestionAnswer (event.question_answers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.question_answers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS question_answers_insert_audit ON event.question_answers;
CREATE TRIGGER question_answers_insert_audit BEFORE INSERT ON event.question_answers
    FOR EACH ROW EXECUTE FUNCTION event.question_answers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS question_answers_update_audit ON event.question_answers;
CREATE TRIGGER question_answers_update_audit BEFORE UPDATE ON event.question_answers
    FOR EACH ROW EXECUTE FUNCTION event.question_answers_audit_timestamp();

-- ==============================================================================
-- Table: RegistrationQuestion (event.registration_questions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.registration_questions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS registration_questions_insert_audit ON event.registration_questions;
CREATE TRIGGER registration_questions_insert_audit BEFORE INSERT ON event.registration_questions
    FOR EACH ROW EXECUTE FUNCTION event.registration_questions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS registration_questions_update_audit ON event.registration_questions;
CREATE TRIGGER registration_questions_update_audit BEFORE UPDATE ON event.registration_questions
    FOR EACH ROW EXECUTE FUNCTION event.registration_questions_audit_timestamp();

-- ==============================================================================
-- Table: Registration (event.registrations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.registrations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS registrations_insert_audit ON event.registrations;
CREATE TRIGGER registrations_insert_audit BEFORE INSERT ON event.registrations
    FOR EACH ROW EXECUTE FUNCTION event.registrations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS registrations_update_audit ON event.registrations;
CREATE TRIGGER registrations_update_audit BEFORE UPDATE ON event.registrations
    FOR EACH ROW EXECUTE FUNCTION event.registrations_audit_timestamp();

-- ==============================================================================
-- Table: RegistrationAnswer (event.registration_answers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.registration_answers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS registration_answers_insert_audit ON event.registration_answers;
CREATE TRIGGER registration_answers_insert_audit BEFORE INSERT ON event.registration_answers
    FOR EACH ROW EXECUTE FUNCTION event.registration_answers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS registration_answers_update_audit ON event.registration_answers;
CREATE TRIGGER registration_answers_update_audit BEFORE UPDATE ON event.registration_answers
    FOR EACH ROW EXECUTE FUNCTION event.registration_answers_audit_timestamp();

-- ==============================================================================
-- Table: Slot (event.slots)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.slots_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS slots_insert_audit ON event.slots;
CREATE TRIGGER slots_insert_audit BEFORE INSERT ON event.slots
    FOR EACH ROW EXECUTE FUNCTION event.slots_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS slots_update_audit ON event.slots;
CREATE TRIGGER slots_update_audit BEFORE UPDATE ON event.slots
    FOR EACH ROW EXECUTE FUNCTION event.slots_audit_timestamp();

-- ==============================================================================
-- Table: Stage (event.stages)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.stages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS stages_insert_audit ON event.stages;
CREATE TRIGGER stages_insert_audit BEFORE INSERT ON event.stages
    FOR EACH ROW EXECUTE FUNCTION event.stages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS stages_update_audit ON event.stages;
CREATE TRIGGER stages_update_audit BEFORE UPDATE ON event.stages
    FOR EACH ROW EXECUTE FUNCTION event.stages_audit_timestamp();

-- ==============================================================================
-- Table: TagCategory (event.tag_categories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.tag_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tag_categories_insert_audit ON event.tag_categories;
CREATE TRIGGER tag_categories_insert_audit BEFORE INSERT ON event.tag_categories
    FOR EACH ROW EXECUTE FUNCTION event.tag_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tag_categories_update_audit ON event.tag_categories;
CREATE TRIGGER tag_categories_update_audit BEFORE UPDATE ON event.tag_categories
    FOR EACH ROW EXECUTE FUNCTION event.tag_categories_audit_timestamp();

-- ==============================================================================
-- Table: Tag (event.tags)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.tags_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tags_insert_audit ON event.tags;
CREATE TRIGGER tags_insert_audit BEFORE INSERT ON event.tags
    FOR EACH ROW EXECUTE FUNCTION event.tags_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tags_update_audit ON event.tags;
CREATE TRIGGER tags_update_audit BEFORE UPDATE ON event.tags
    FOR EACH ROW EXECUTE FUNCTION event.tags_audit_timestamp();

-- ==============================================================================
-- Table: Ticket (event.tickets)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.tickets_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tickets_insert_audit ON event.tickets;
CREATE TRIGGER tickets_insert_audit BEFORE INSERT ON event.tickets
    FOR EACH ROW EXECUTE FUNCTION event.tickets_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tickets_update_audit ON event.tickets;
CREATE TRIGGER tickets_update_audit BEFORE UPDATE ON event.tickets
    FOR EACH ROW EXECUTE FUNCTION event.tickets_audit_timestamp();

-- ==============================================================================
-- Table: TypeMail (event.type_mails)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION event.type_mails_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS type_mails_insert_audit ON event.type_mails;
CREATE TRIGGER type_mails_insert_audit BEFORE INSERT ON event.type_mails
    FOR EACH ROW EXECUTE FUNCTION event.type_mails_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS type_mails_update_audit ON event.type_mails;
CREATE TRIGGER type_mails_update_audit BEFORE UPDATE ON event.type_mails
    FOR EACH ROW EXECUTE FUNCTION event.type_mails_audit_timestamp();

