-- Migration: Create events table
-- Generated by metaphor-schema

-- Create event_kanban_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_kanban_state') THEN
        CREATE TYPE event_kanban_state AS ENUM ('normal', 'done', 'blocked', 'cancel');
    END IF;
END
$$;

-- Create event_badge_format enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_badge_format') THEN
        CREATE TYPE event_badge_format AS ENUM ('a4_french_fold', 'a6', 'four_per_sheet');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.events (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    event_type_id UUID,
    stage_id UUID NOT NULL,
    kanban_state event_kanban_state NOT NULL DEFAULT 'normal',
    date_begin TIMESTAMPTZ NOT NULL,
    date_end TIMESTAMPTZ NOT NULL,
    date_tz TEXT NOT NULL DEFAULT 'UTC',
    is_multi_slots BOOLEAN NOT NULL DEFAULT FALSE,
    event_slot_count INTEGER NOT NULL DEFAULT 1,
    seats_limited BOOLEAN NOT NULL DEFAULT FALSE,
    seats_max INTEGER NOT NULL DEFAULT 0 CHECK (seats_max >= 0),
    address_id UUID,
    organizer_id UUID,
    user_id UUID,
    company_id UUID,
    event_url TEXT,
    badge_format event_badge_format NOT NULL DEFAULT 'a4_french_fold',
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    date_publish TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_events_date_begin_date_end ON event.events (date_begin, date_end);

CREATE INDEX IF NOT EXISTS idx_events_is_published ON event.events (is_published);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_events_metadata_gin ON event.events USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_events_metadata_deleted_at ON event.events ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_events_metadata_created_at ON event.events ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_events_metadata_updated_at ON event.events ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.events_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS events_insert_audit ON event.events;
CREATE TRIGGER events_insert_audit BEFORE INSERT ON event.events
    FOR EACH ROW EXECUTE FUNCTION event.events_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS events_update_audit ON event.events;
CREATE TRIGGER events_update_audit BEFORE UPDATE ON event.events
    FOR EACH ROW EXECUTE FUNCTION event.events_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE event.events ADD CONSTRAINT fk_events_event_type_id FOREIGN KEY (event_type_id) REFERENCES event.types (id);
ALTER TABLE event.events ADD CONSTRAINT fk_events_stage_id FOREIGN KEY (stage_id) REFERENCES event.stages (id);
