-- Migration: Create question_answers table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.question_answers (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    question_id UUID NOT NULL,
    name TEXT NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 1 CHECK (sequence >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_question_answers_metadata_gin ON event.question_answers USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_question_answers_metadata_deleted_at ON event.question_answers ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_question_answers_metadata_created_at ON event.question_answers ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_question_answers_metadata_updated_at ON event.question_answers ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.question_answers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS question_answers_insert_audit ON event.question_answers;
CREATE TRIGGER question_answers_insert_audit BEFORE INSERT ON event.question_answers
    FOR EACH ROW EXECUTE FUNCTION event.question_answers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS question_answers_update_audit ON event.question_answers;
CREATE TRIGGER question_answers_update_audit BEFORE UPDATE ON event.question_answers
    FOR EACH ROW EXECUTE FUNCTION event.question_answers_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE event.question_answers ADD CONSTRAINT fk_question_answers_question_id FOREIGN KEY (question_id) REFERENCES event.questions (id);
