-- Migration: Create lead_rules table
-- Generated by metaphor-schema

-- Create event_lead_basis enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_lead_basis') THEN
        CREATE TYPE event_lead_basis AS ENUM ('registration', 'attendee');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.lead_rules (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    event_id UUID,
    basis event_lead_basis NOT NULL DEFAULT 'registration',
    on_create BOOLEAN NOT NULL DEFAULT FALSE,
    on_confirm BOOLEAN NOT NULL DEFAULT FALSE,
    on_done BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_lead_rules_event_id_active ON event.lead_rules (event_id, active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_lead_rules_metadata_gin ON event.lead_rules USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_lead_rules_metadata_deleted_at ON event.lead_rules ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_lead_rules_metadata_created_at ON event.lead_rules ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_lead_rules_metadata_updated_at ON event.lead_rules ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.lead_rules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS lead_rules_insert_audit ON event.lead_rules;
CREATE TRIGGER lead_rules_insert_audit BEFORE INSERT ON event.lead_rules
    FOR EACH ROW EXECUTE FUNCTION event.lead_rules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS lead_rules_update_audit ON event.lead_rules;
CREATE TRIGGER lead_rules_update_audit BEFORE UPDATE ON event.lead_rules
    FOR EACH ROW EXECUTE FUNCTION event.lead_rules_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE event.lead_rules ADD CONSTRAINT fk_lead_rules_event_id FOREIGN KEY (event_id) REFERENCES event.events (id);
