-- Migration: Create event_audit_log table
-- Generated by metaphor-schema

-- Create event_audit_event enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_audit_event') THEN
        CREATE TYPE event_audit_event AS ENUM ('event_created', 'event_updated', 'event_published', 'event_unpublished', 'publish_refused', 'event_mark_done', 'registration_created', 'registration_refused', 'registration_state_changed', 'registration_archived', 'scheduler_created', 'scheduler_run', 'scheduler_failed', 'receipt_dropped_window_closed', 'capability_refused');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.event_audit_log (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    event event_audit_event NOT NULL,
    actor UUID,
    subject_type TEXT,
    subject_id UUID,
    detail JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_event_audit_log_event_occurred_at ON event.event_audit_log (event, occurred_at);
