-- Migration: Create registration_questions table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.registration_questions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    event_id UUID,
    event_type_id UUID,
    question_id UUID NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 1 CHECK (sequence >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_registration_questions_event_id_question_id ON event.registration_questions (event_id, question_id) WHERE event_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_registration_questions_event_type_id_question_id ON event.registration_questions (event_type_id, question_id) WHERE event_type_id IS NOT NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_registration_questions_metadata_gin ON event.registration_questions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_registration_questions_metadata_deleted_at ON event.registration_questions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_registration_questions_metadata_created_at ON event.registration_questions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_registration_questions_metadata_updated_at ON event.registration_questions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.registration_questions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS registration_questions_insert_audit ON event.registration_questions;
CREATE TRIGGER registration_questions_insert_audit BEFORE INSERT ON event.registration_questions
    FOR EACH ROW EXECUTE FUNCTION event.registration_questions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS registration_questions_update_audit ON event.registration_questions;
CREATE TRIGGER registration_questions_update_audit BEFORE UPDATE ON event.registration_questions
    FOR EACH ROW EXECUTE FUNCTION event.registration_questions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE event.registration_questions ADD CONSTRAINT fk_registration_questions_event_id FOREIGN KEY (event_id) REFERENCES event.events (id);
ALTER TABLE event.registration_questions ADD CONSTRAINT fk_registration_questions_event_type_id FOREIGN KEY (event_type_id) REFERENCES event.types (id);
ALTER TABLE event.registration_questions ADD CONSTRAINT fk_registration_questions_question_id FOREIGN KEY (question_id) REFERENCES event.questions (id);
