-- Migration: Create questions table
-- Generated by metaphor-schema

-- Create event_question_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_question_kind') THEN
        CREATE TYPE event_question_kind AS ENUM ('text_box', 'simple_choice', 'name', 'email', 'phone', 'company_name');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.questions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    question TEXT NOT NULL,
    question_kind event_question_kind NOT NULL DEFAULT 'text_box',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_reusable BOOLEAN NOT NULL DEFAULT FALSE,
    once_per_order BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_questions_question_kind ON event.questions (question_kind);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_questions_metadata_gin ON event.questions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_questions_metadata_deleted_at ON event.questions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_questions_metadata_created_at ON event.questions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_questions_metadata_updated_at ON event.questions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION event.questions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS questions_insert_audit ON event.questions;
CREATE TRIGGER questions_insert_audit BEFORE INSERT ON event.questions
    FOR EACH ROW EXECUTE FUNCTION event.questions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS questions_update_audit ON event.questions;
CREATE TRIGGER questions_update_audit BEFORE UPDATE ON event.questions
    FOR EACH ROW EXECUTE FUNCTION event.questions_audit_timestamp();
