//! Event handler trait for BoothBooking events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BoothBookingEvent;

/// Event handler for BoothBooking events.
/// Implement this trait to react to BoothBooking lifecycle events.
pub trait BoothBookingEventHandler: EventHandler<BoothBookingEvent> {}
