//! Domain events for BoothBooking entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BoothBooking;

/// Domain events for BoothBooking — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BoothBooking>)` variant.
pub type BoothBookingEvent = CrudEvent<BoothBooking>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BoothBooking events.
pub type BoothBookingEventPublisher = Arc<dyn CrudEventPublisher<BoothBooking> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBoothBookingEventPublisher = NoOpCrudEventPublisher<BoothBooking>;
