//! Event handler trait for EventType events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EventTypeEvent;

/// Event handler for EventType events.
/// Implement this trait to react to EventType lifecycle events.
pub trait EventTypeEventHandler: EventHandler<EventTypeEvent> {}
