//! Domain events for EventAuditLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EventAuditLog;

/// Domain events for EventAuditLog — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EventAuditLog>)` variant.
pub type EventAuditLogEvent = CrudEvent<EventAuditLog>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EventAuditLog events.
pub type EventAuditLogEventPublisher = Arc<dyn CrudEventPublisher<EventAuditLog> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEventAuditLogEventPublisher = NoOpCrudEventPublisher<EventAuditLog>;
