//! Event handler trait for EventAuditLog events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EventAuditLogEvent;

/// Event handler for EventAuditLog events.
/// Implement this trait to react to EventAuditLog lifecycle events.
pub trait EventAuditLogEventHandler: EventHandler<EventAuditLogEvent> {}
