//! Domain events for EventType entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EventType;

/// Domain events for EventType — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EventType>)` variant.
pub type EventTypeEvent = CrudEvent<EventType>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EventType events.
pub type EventTypeEventPublisher = Arc<dyn CrudEventPublisher<EventType> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEventTypeEventPublisher = NoOpCrudEventPublisher<EventType>;
