//! Event handler trait for LeadRulePredicate events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LeadRulePredicateEvent;

/// Event handler for LeadRulePredicate events.
/// Implement this trait to react to LeadRulePredicate lifecycle events.
pub trait LeadRulePredicateEventHandler: EventHandler<LeadRulePredicateEvent> {}
