//! Event handler trait for LeadRule events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LeadRuleEvent;

/// Event handler for LeadRule events.
/// Implement this trait to react to LeadRule lifecycle events.
pub trait LeadRuleEventHandler: EventHandler<LeadRuleEvent> {}
