//! Domain events for LeadRulePredicate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::LeadRulePredicate;

/// Domain events for LeadRulePredicate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<LeadRulePredicate>)` variant.
pub type LeadRulePredicateEvent = CrudEvent<LeadRulePredicate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for LeadRulePredicate events.
pub type LeadRulePredicateEventPublisher = Arc<dyn CrudEventPublisher<LeadRulePredicate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLeadRulePredicateEventPublisher = NoOpCrudEventPublisher<LeadRulePredicate>;
