//! Domain events for LeadProvenance entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::LeadProvenance;

/// Domain events for LeadProvenance — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<LeadProvenance>)` variant.
pub type LeadProvenanceEvent = CrudEvent<LeadProvenance>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for LeadProvenance events.
pub type LeadProvenanceEventPublisher = Arc<dyn CrudEventPublisher<LeadProvenance> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLeadProvenanceEventPublisher = NoOpCrudEventPublisher<LeadProvenance>;
