//! Event handler trait for LeadProvenanceRegistration events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LeadProvenanceRegistrationEvent;

/// Event handler for LeadProvenanceRegistration events.
/// Implement this trait to react to LeadProvenanceRegistration lifecycle events.
pub trait LeadProvenanceRegistrationEventHandler: EventHandler<LeadProvenanceRegistrationEvent> {}
