//! Event handler trait for LeadRequest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LeadRequestEvent;

/// Event handler for LeadRequest events.
/// Implement this trait to react to LeadRequest lifecycle events.
pub trait LeadRequestEventHandler: EventHandler<LeadRequestEvent> {}
