//! Event handler trait for MailRegistration events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailRegistrationEvent;

/// Event handler for MailRegistration events.
/// Implement this trait to react to MailRegistration lifecycle events.
pub trait MailRegistrationEventHandler: EventHandler<MailRegistrationEvent> {}
