//! Event handler trait for MailSlot events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailSlotEvent;

/// Event handler for MailSlot events.
/// Implement this trait to react to MailSlot lifecycle events.
pub trait MailSlotEventHandler: EventHandler<MailSlotEvent> {}
