//! Domain events for MailSlot entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailSlot;

/// Domain events for MailSlot — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailSlot>)` variant.
pub type MailSlotEvent = CrudEvent<MailSlot>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailSlot events.
pub type MailSlotEventPublisher = Arc<dyn CrudEventPublisher<MailSlot> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailSlotEventPublisher = NoOpCrudEventPublisher<MailSlot>;
