//! Event handler trait for RegistrationQuestion events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RegistrationQuestionEvent;

/// Event handler for RegistrationQuestion events.
/// Implement this trait to react to RegistrationQuestion lifecycle events.
pub trait RegistrationQuestionEventHandler: EventHandler<RegistrationQuestionEvent> {}
