//! Event handler trait for RegistrationAnswer events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RegistrationAnswerEvent;

/// Event handler for RegistrationAnswer events.
/// Implement this trait to react to RegistrationAnswer lifecycle events.
pub trait RegistrationAnswerEventHandler: EventHandler<RegistrationAnswerEvent> {}
