//! Domain events for RegistrationAnswer entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RegistrationAnswer;

/// Domain events for RegistrationAnswer — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RegistrationAnswer>)` variant.
pub type RegistrationAnswerEvent = CrudEvent<RegistrationAnswer>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RegistrationAnswer events.
pub type RegistrationAnswerEventPublisher = Arc<dyn CrudEventPublisher<RegistrationAnswer> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRegistrationAnswerEventPublisher = NoOpCrudEventPublisher<RegistrationAnswer>;
