//! Domain events for Slot entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Slot;

/// Domain events for Slot — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Slot>)` variant.
pub type SlotEvent = CrudEvent<Slot>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Slot events.
pub type SlotEventPublisher = Arc<dyn CrudEventPublisher<Slot> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSlotEventPublisher = NoOpCrudEventPublisher<Slot>;
