//! Event handler trait for TagCategory events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TagCategoryEvent;

/// Event handler for TagCategory events.
/// Implement this trait to react to TagCategory lifecycle events.
pub trait TagCategoryEventHandler: EventHandler<TagCategoryEvent> {}
