//! Event handler trait for Tag events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TagEvent;

/// Event handler for Tag events.
/// Implement this trait to react to Tag lifecycle events.
pub trait TagEventHandler: EventHandler<TagEvent> {}
