//! Domain events for Ticket entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Ticket;

/// Domain events for Ticket — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Ticket>)` variant.
pub type TicketEvent = CrudEvent<Ticket>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Ticket events.
pub type TicketEventPublisher = Arc<dyn CrudEventPublisher<Ticket> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTicketEventPublisher = NoOpCrudEventPublisher<Ticket>;
