//! Event handler trait for TypeBooth events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TypeBoothEvent;

/// Event handler for TypeBooth events.
/// Implement this trait to react to TypeBooth lifecycle events.
pub trait TypeBoothEventHandler: EventHandler<TypeBoothEvent> {}
