//! Event handler trait for TypeMail events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TypeMailEvent;

/// Event handler for TypeMail events.
/// Implement this trait to react to TypeMail lifecycle events.
pub trait TypeMailEventHandler: EventHandler<TypeMailEvent> {}
