//! Event seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Event data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// EVENT SEEDER
// ============================================================================

/// Seeder for event
pub struct SeedEventSeeder;

impl SeedEventSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedEventSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedEventSeeder {
    fn name(&self) -> &'static str {
        "SeedEventSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if event.events table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM event.events")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/event_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM event.events")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
