//! LeadRulePredicate seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial LeadRulePredicate data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// LEADRULEPREDICATE SEEDER
// ============================================================================

/// Seeder for lead_rule_predicate
pub struct SeedLeadRulePredicateSeeder;

impl SeedLeadRulePredicateSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedLeadRulePredicateSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedLeadRulePredicateSeeder {
    fn name(&self) -> &'static str {
        "SeedLeadRulePredicateSeeder"
    }

    fn order(&self) -> i32 {
        12
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if event.lead_rule_predicates table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM event.lead_rule_predicates")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/lead_rule_predicate_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM event.lead_rule_predicates")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
