//! MailSlot seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MailSlot data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MAILSLOT SEEDER
// ============================================================================

/// Seeder for mail_slot
pub struct SeedMailSlotSeeder;

impl SeedMailSlotSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMailSlotSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMailSlotSeeder {
    fn name(&self) -> &'static str {
        "SeedMailSlotSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if event.mail_slots table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM event.mail_slots")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/mail_slot_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM event.mail_slots")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
