//! TagCategory seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TagCategory data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TAGCATEGORY SEEDER
// ============================================================================

/// Seeder for tag_category
pub struct SeedTagCategorySeeder;

impl SeedTagCategorySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTagCategorySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTagCategorySeeder {
    fn name(&self) -> &'static str {
        "SeedTagCategorySeeder"
    }

    fn order(&self) -> i32 {
        23
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if event.tag_categories table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM event.tag_categories")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/tag_category_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM event.tag_categories")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
