//! Ticket seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Ticket data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TICKET SEEDER
// ============================================================================

/// Seeder for ticket
pub struct SeedTicketSeeder;

impl SeedTicketSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTicketSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTicketSeeder {
    fn name(&self) -> &'static str {
        "SeedTicketSeeder"
    }

    fn order(&self) -> i32 {
        16
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if event.tickets table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM event.tickets")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/ticket_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM event.tickets")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
