//! TypeMail seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TypeMail data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TYPEMAIL SEEDER
// ============================================================================

/// Seeder for type_mail
pub struct SeedTypeMailSeeder;

impl SeedTypeMailSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTypeMailSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTypeMailSeeder {
    fn name(&self) -> &'static str {
        "SeedTypeMailSeeder"
    }

    fn order(&self) -> i32 {
        26
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if event.type_mails table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM event.type_mails")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/type_mail_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM event.type_mails")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
