//! Repository trait for Booth aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Booth aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Booth, EventBoothState};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BoothPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BoothPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BoothPaginatedResult {
    pub data: Vec<Booth>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BoothFilter {
    pub event_id: Option<Uuid>,
    pub booth_category_id: Option<Uuid>,
    pub name: Option<String>,
    pub state: Option<EventBoothState>,
    pub partner_id: Option<Uuid>,
    pub contact_name: Option<String>,
    pub contact_email: Option<String>,
    pub contact_phone: Option<String>,
    pub sale_order_line_id: Option<Uuid>,
    pub is_paid: Option<bool>,
}

impl BoothFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.event_id.is_some() || self.booth_category_id.is_some() || self.name.is_some() || self.state.is_some() || self.partner_id.is_some() || self.contact_name.is_some() || self.contact_email.is_some() || self.contact_phone.is_some() || self.sale_order_line_id.is_some() || self.is_paid.is_some()
    }
}

/// Repository trait for Booth aggregate
///
/// This trait defines the persistence contract for Booth entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BoothRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new booth entity
    async fn save(&self, entity: &Booth) -> Result<Booth>;

    /// Find booth by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Booth>>;

    /// Find all booth entities
    async fn find_all(&self) -> Result<Vec<Booth>>;

    /// Update booth by ID
    async fn update(&self, id: &str, entity: &Booth) -> Result<Option<Booth>>;

    /// Delete booth by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List booth with pagination
    async fn list(&self, params: BoothPaginationParams) -> Result<BoothPaginatedResult>;

    /// List booth with pagination and filters
    async fn list_with_filters(&self, params: BoothPaginationParams, filters: BoothFilter) -> Result<BoothPaginatedResult>;

    /// Count all booth entities
    async fn count(&self) -> Result<u64>;

    /// Count booth entities matching filters
    async fn count_with_filters(&self, filters: BoothFilter) -> Result<u64>;

    /// Check if booth exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete booth by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted booth by ID
    async fn restore(&self, id: &str) -> Result<Option<Booth>>;

    /// List soft-deleted booth entities
    async fn list_deleted(&self, params: BoothPaginationParams) -> Result<BoothPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save booth entities
    async fn bulk_save(&self, entities: &[Booth]) -> Result<Vec<Booth>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
