//! Repository trait for EventType aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EventType aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::EventType;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EventTypePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EventTypePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EventTypePaginatedResult {
    pub data: Vec<EventType>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EventTypeFilter {
    pub name: Option<String>,
    pub description: Option<String>,
    pub seats_limited: Option<bool>,
    pub default_date_tz: Option<String>,
    pub is_multi_slots: Option<bool>,
}

impl EventTypeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.description.is_some() || self.seats_limited.is_some() || self.default_date_tz.is_some() || self.is_multi_slots.is_some()
    }
}

/// Repository trait for EventType aggregate
///
/// This trait defines the persistence contract for EventType entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EventTypeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new event_type entity
    async fn save(&self, entity: &EventType) -> Result<EventType>;

    /// Find event_type by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EventType>>;

    /// Find all event_type entities
    async fn find_all(&self) -> Result<Vec<EventType>>;

    /// Update event_type by ID
    async fn update(&self, id: &str, entity: &EventType) -> Result<Option<EventType>>;

    /// Delete event_type by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List event_type with pagination
    async fn list(&self, params: EventTypePaginationParams) -> Result<EventTypePaginatedResult>;

    /// List event_type with pagination and filters
    async fn list_with_filters(&self, params: EventTypePaginationParams, filters: EventTypeFilter) -> Result<EventTypePaginatedResult>;

    /// Count all event_type entities
    async fn count(&self) -> Result<u64>;

    /// Count event_type entities matching filters
    async fn count_with_filters(&self, filters: EventTypeFilter) -> Result<u64>;

    /// Check if event_type exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete event_type by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted event_type by ID
    async fn restore(&self, id: &str) -> Result<Option<EventType>>;

    /// List soft-deleted event_type entities
    async fn list_deleted(&self, params: EventTypePaginationParams) -> Result<EventTypePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save event_type entities
    async fn bulk_save(&self, entities: &[EventType]) -> Result<Vec<EventType>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
