//! Repository trait for LeadProvenance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the LeadProvenance aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{LeadProvenance, EventLeadGrouping};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LeadProvenancePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl LeadProvenancePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct LeadProvenancePaginatedResult {
    pub data: Vec<LeadProvenance>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LeadProvenanceFilter {
    pub rule_id: Option<Uuid>,
    pub event_id: Option<Uuid>,
    pub lead_id: Option<Uuid>,
    pub group_key: Option<String>,
    pub grouping: Option<EventLeadGrouping>,
}

impl LeadProvenanceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.rule_id.is_some() || self.event_id.is_some() || self.lead_id.is_some() || self.group_key.is_some() || self.grouping.is_some()
    }
}

/// Repository trait for LeadProvenance aggregate
///
/// This trait defines the persistence contract for LeadProvenance entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait LeadProvenanceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new lead_provenance entity
    async fn save(&self, entity: &LeadProvenance) -> Result<LeadProvenance>;

    /// Find lead_provenance by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<LeadProvenance>>;

    /// Find all lead_provenance entities
    async fn find_all(&self) -> Result<Vec<LeadProvenance>>;

    /// Update lead_provenance by ID
    async fn update(&self, id: &str, entity: &LeadProvenance) -> Result<Option<LeadProvenance>>;

    /// Delete lead_provenance by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List lead_provenance with pagination
    async fn list(&self, params: LeadProvenancePaginationParams) -> Result<LeadProvenancePaginatedResult>;

    /// List lead_provenance with pagination and filters
    async fn list_with_filters(&self, params: LeadProvenancePaginationParams, filters: LeadProvenanceFilter) -> Result<LeadProvenancePaginatedResult>;

    /// Count all lead_provenance entities
    async fn count(&self) -> Result<u64>;

    /// Count lead_provenance entities matching filters
    async fn count_with_filters(&self, filters: LeadProvenanceFilter) -> Result<u64>;

    /// Check if lead_provenance exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete lead_provenance by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted lead_provenance by ID
    async fn restore(&self, id: &str) -> Result<Option<LeadProvenance>>;

    /// List soft-deleted lead_provenance entities
    async fn list_deleted(&self, params: LeadProvenancePaginationParams) -> Result<LeadProvenancePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save lead_provenance entities
    async fn bulk_save(&self, entities: &[LeadProvenance]) -> Result<Vec<LeadProvenance>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
