//! Repository trait for RegistrationAnswer aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the RegistrationAnswer aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::RegistrationAnswer;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RegistrationAnswerPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RegistrationAnswerPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RegistrationAnswerPaginatedResult {
    pub data: Vec<RegistrationAnswer>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RegistrationAnswerFilter {
    pub registration_id: Option<Uuid>,
    pub question_id: Option<Uuid>,
    pub value_text: Option<String>,
    pub value_answer_id: Option<Uuid>,
}

impl RegistrationAnswerFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.registration_id.is_some() || self.question_id.is_some() || self.value_text.is_some() || self.value_answer_id.is_some()
    }
}

/// Repository trait for RegistrationAnswer aggregate
///
/// This trait defines the persistence contract for RegistrationAnswer entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RegistrationAnswerRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new registration_answer entity
    async fn save(&self, entity: &RegistrationAnswer) -> Result<RegistrationAnswer>;

    /// Find registration_answer by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<RegistrationAnswer>>;

    /// Find all registration_answer entities
    async fn find_all(&self) -> Result<Vec<RegistrationAnswer>>;

    /// Update registration_answer by ID
    async fn update(&self, id: &str, entity: &RegistrationAnswer) -> Result<Option<RegistrationAnswer>>;

    /// Delete registration_answer by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List registration_answer with pagination
    async fn list(&self, params: RegistrationAnswerPaginationParams) -> Result<RegistrationAnswerPaginatedResult>;

    /// List registration_answer with pagination and filters
    async fn list_with_filters(&self, params: RegistrationAnswerPaginationParams, filters: RegistrationAnswerFilter) -> Result<RegistrationAnswerPaginatedResult>;

    /// Count all registration_answer entities
    async fn count(&self) -> Result<u64>;

    /// Count registration_answer entities matching filters
    async fn count_with_filters(&self, filters: RegistrationAnswerFilter) -> Result<u64>;

    /// Check if registration_answer exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete registration_answer by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted registration_answer by ID
    async fn restore(&self, id: &str) -> Result<Option<RegistrationAnswer>>;

    /// List soft-deleted registration_answer entities
    async fn list_deleted(&self, params: RegistrationAnswerPaginationParams) -> Result<RegistrationAnswerPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save registration_answer entities
    async fn bulk_save(&self, entities: &[RegistrationAnswer]) -> Result<Vec<RegistrationAnswer>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
