//! Repository trait for Slot aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Slot aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Slot;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SlotPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SlotPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SlotPaginatedResult {
    pub data: Vec<Slot>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SlotFilter {
    pub event_id: Option<Uuid>,
    pub name: Option<String>,
}

impl SlotFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.event_id.is_some() || self.name.is_some()
    }
}

/// Repository trait for Slot aggregate
///
/// This trait defines the persistence contract for Slot entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SlotRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new slot entity
    async fn save(&self, entity: &Slot) -> Result<Slot>;

    /// Find slot by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Slot>>;

    /// Find all slot entities
    async fn find_all(&self) -> Result<Vec<Slot>>;

    /// Update slot by ID
    async fn update(&self, id: &str, entity: &Slot) -> Result<Option<Slot>>;

    /// Delete slot by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List slot with pagination
    async fn list(&self, params: SlotPaginationParams) -> Result<SlotPaginatedResult>;

    /// List slot with pagination and filters
    async fn list_with_filters(&self, params: SlotPaginationParams, filters: SlotFilter) -> Result<SlotPaginatedResult>;

    /// Count all slot entities
    async fn count(&self) -> Result<u64>;

    /// Count slot entities matching filters
    async fn count_with_filters(&self, filters: SlotFilter) -> Result<u64>;

    /// Check if slot exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete slot by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted slot by ID
    async fn restore(&self, id: &str) -> Result<Option<Slot>>;

    /// List soft-deleted slot entities
    async fn list_deleted(&self, params: SlotPaginationParams) -> Result<SlotPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save slot entities
    async fn bulk_save(&self, entities: &[Slot]) -> Result<Vec<Slot>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
