//! Repository trait for TagCategory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TagCategory aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::TagCategory;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TagCategoryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TagCategoryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TagCategoryPaginatedResult {
    pub data: Vec<TagCategory>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TagCategoryFilter {
    pub name: Option<String>,
}

impl TagCategoryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some()
    }
}

/// Repository trait for TagCategory aggregate
///
/// This trait defines the persistence contract for TagCategory entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TagCategoryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new tag_category entity
    async fn save(&self, entity: &TagCategory) -> Result<TagCategory>;

    /// Find tag_category by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TagCategory>>;

    /// Find all tag_category entities
    async fn find_all(&self) -> Result<Vec<TagCategory>>;

    /// Update tag_category by ID
    async fn update(&self, id: &str, entity: &TagCategory) -> Result<Option<TagCategory>>;

    /// Delete tag_category by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List tag_category with pagination
    async fn list(&self, params: TagCategoryPaginationParams) -> Result<TagCategoryPaginatedResult>;

    /// List tag_category with pagination and filters
    async fn list_with_filters(&self, params: TagCategoryPaginationParams, filters: TagCategoryFilter) -> Result<TagCategoryPaginatedResult>;

    /// Count all tag_category entities
    async fn count(&self) -> Result<u64>;

    /// Count tag_category entities matching filters
    async fn count_with_filters(&self, filters: TagCategoryFilter) -> Result<u64>;

    /// Check if tag_category exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete tag_category by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted tag_category by ID
    async fn restore(&self, id: &str) -> Result<Option<TagCategory>>;

    /// List soft-deleted tag_category entities
    async fn list_deleted(&self, params: TagCategoryPaginationParams) -> Result<TagCategoryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save tag_category entities
    async fn bulk_save(&self, entities: &[TagCategory]) -> Result<Vec<TagCategory>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
