//! Repository trait for TypeMail aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TypeMail aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{TypeMail, EventIntervalKind, EventIntervalUnit, EventNotificationChannel};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TypeMailPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TypeMailPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TypeMailPaginatedResult {
    pub data: Vec<TypeMail>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TypeMailFilter {
    pub event_type_id: Option<Uuid>,
    pub interval_unit: Option<EventIntervalUnit>,
    pub interval_kind: Option<EventIntervalKind>,
    pub notification_channel: Option<EventNotificationChannel>,
    pub template_ref: Option<Uuid>,
    pub template_kind: Option<String>,
}

impl TypeMailFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.event_type_id.is_some() || self.interval_unit.is_some() || self.interval_kind.is_some() || self.notification_channel.is_some() || self.template_ref.is_some() || self.template_kind.is_some()
    }
}

/// Repository trait for TypeMail aggregate
///
/// This trait defines the persistence contract for TypeMail entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TypeMailRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new type_mail entity
    async fn save(&self, entity: &TypeMail) -> Result<TypeMail>;

    /// Find type_mail by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TypeMail>>;

    /// Find all type_mail entities
    async fn find_all(&self) -> Result<Vec<TypeMail>>;

    /// Update type_mail by ID
    async fn update(&self, id: &str, entity: &TypeMail) -> Result<Option<TypeMail>>;

    /// Delete type_mail by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List type_mail with pagination
    async fn list(&self, params: TypeMailPaginationParams) -> Result<TypeMailPaginatedResult>;

    /// List type_mail with pagination and filters
    async fn list_with_filters(&self, params: TypeMailPaginationParams, filters: TypeMailFilter) -> Result<TypeMailPaginatedResult>;

    /// Count all type_mail entities
    async fn count(&self) -> Result<u64>;

    /// Count type_mail entities matching filters
    async fn count_with_filters(&self, filters: TypeMailFilter) -> Result<u64>;

    /// Check if type_mail exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete type_mail by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted type_mail by ID
    async fn restore(&self, id: &str) -> Result<Option<TypeMail>>;

    /// List soft-deleted type_mail entities
    async fn list_deleted(&self, params: TypeMailPaginationParams) -> Result<TypeMailPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save type_mail entities
    async fn bulk_save(&self, entities: &[TypeMail]) -> Result<Vec<TypeMail>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
