//! Repository trait for TypeBooth aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TypeBooth aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::TypeBooth;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TypeBoothPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TypeBoothPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TypeBoothPaginatedResult {
    pub data: Vec<TypeBooth>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TypeBoothFilter {
    pub event_type_id: Option<Uuid>,
    pub booth_category_id: Option<Uuid>,
    pub name: Option<String>,
}

impl TypeBoothFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.event_type_id.is_some() || self.booth_category_id.is_some() || self.name.is_some()
    }
}

/// Repository trait for TypeBooth aggregate
///
/// This trait defines the persistence contract for TypeBooth entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TypeBoothRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new type_booth entity
    async fn save(&self, entity: &TypeBooth) -> Result<TypeBooth>;

    /// Find type_booth by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TypeBooth>>;

    /// Find all type_booth entities
    async fn find_all(&self) -> Result<Vec<TypeBooth>>;

    /// Update type_booth by ID
    async fn update(&self, id: &str, entity: &TypeBooth) -> Result<Option<TypeBooth>>;

    /// Delete type_booth by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List type_booth with pagination
    async fn list(&self, params: TypeBoothPaginationParams) -> Result<TypeBoothPaginatedResult>;

    /// List type_booth with pagination and filters
    async fn list_with_filters(&self, params: TypeBoothPaginationParams, filters: TypeBoothFilter) -> Result<TypeBoothPaginatedResult>;

    /// Count all type_booth entities
    async fn count(&self) -> Result<u64>;

    /// Count type_booth entities matching filters
    async fn count_with_filters(&self, filters: TypeBoothFilter) -> Result<u64>;

    /// Check if type_booth exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete type_booth by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted type_booth by ID
    async fn restore(&self, id: &str) -> Result<Option<TypeBooth>>;

    /// List soft-deleted type_booth entities
    async fn list_deleted(&self, params: TypeBoothPaginationParams) -> Result<TypeBoothPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save type_booth entities
    async fn bulk_save(&self, entities: &[TypeBooth]) -> Result<Vec<TypeBooth>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
