//! Repository for EventAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EventAuditLog, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EventAuditLog;

/// Table name for EventAuditLog entities
pub const TABLE_NAME: &str = "event.event_audit_log";

/// Repository for EventAuditLog entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EventAuditLogRepository(
    backbone_orm::GenericCrudRepository<EventAuditLog, backbone_orm::HardDelete>,
);

impl std::ops::Deref for EventAuditLogRepository {
    type Target = backbone_orm::GenericCrudRepository<EventAuditLog, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EventAuditLogRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EventAuditLogRepository, EventAuditLog, no_soft_delete);
