//! Repository for MailSlot entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailSlot, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailSlot;

/// Table name for MailSlot entities
pub const TABLE_NAME: &str = "event.mail_slots";

/// Repository for MailSlot entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailSlotRepository(
    backbone_orm::GenericCrudRepository<MailSlot, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailSlotRepository {
    type Target = backbone_orm::GenericCrudRepository<MailSlot, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailSlotRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailSlotRepository, MailSlot, soft_delete);
