//! Repository for Slot entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Slot, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Slot;

/// Table name for Slot entities
pub const TABLE_NAME: &str = "event.slots";

/// Repository for Slot entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SlotRepository(
    backbone_orm::GenericCrudRepository<Slot, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SlotRepository {
    type Target = backbone_orm::GenericCrudRepository<Slot, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SlotRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SlotRepository, Slot, soft_delete);
