//! Repository for Stage entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Stage, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Stage;

/// Table name for Stage entities
pub const TABLE_NAME: &str = "event.stages";

/// Repository for Stage entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct StageRepository(
    backbone_orm::GenericCrudRepository<Stage, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for StageRepository {
    type Target = backbone_orm::GenericCrudRepository<Stage, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl StageRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(StageRepository, Stage, soft_delete);
