//! Repository for TypeMail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TypeMail, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TypeMail;

/// Table name for TypeMail entities
pub const TABLE_NAME: &str = "event.type_mails";

/// Repository for TypeMail entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TypeMailRepository(
    backbone_orm::GenericCrudRepository<TypeMail, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TypeMailRepository {
    type Target = backbone_orm::GenericCrudRepository<TypeMail, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TypeMailRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TypeMailRepository, TypeMail, soft_delete);
