//! Repository for TypeBooth entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TypeBooth, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TypeBooth;

/// Table name for TypeBooth entities
pub const TABLE_NAME: &str = "event.type_booths";

/// Repository for TypeBooth entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TypeBoothRepository(
    backbone_orm::GenericCrudRepository<TypeBooth, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TypeBoothRepository {
    type Target = backbone_orm::GenericCrudRepository<TypeBooth, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TypeBoothRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TypeBoothRepository, TypeBooth, soft_delete);
