//! Validator for EventType entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EventType>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::EventType;

/// Validator type alias for EventType entities.
pub type EventTypeValidator = EntityValidator<EventType>;

/// Build a validator for EventType with all schema-defined field rules.
pub fn event_type_validator() -> EventTypeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &EventType| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &EventType| e.description.as_deref()))
        .rule(NonNegative::new("seats_max", |e: &EventType| e.seats_max as i64))
        .rule(RequiredString::new("default_date_tz", |e: &EventType| &e.default_date_tz))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
