//! Validator for LeadRulePredicate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<LeadRulePredicate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::LeadRulePredicate;

/// Validator type alias for LeadRulePredicate entities.
pub type LeadRulePredicateValidator = EntityValidator<LeadRulePredicate>;

/// Build a validator for LeadRulePredicate with all schema-defined field rules.
pub fn lead_rule_predicate_validator() -> LeadRulePredicateValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
