//! Validator for Mail entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Mail>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::Mail;

/// Validator type alias for Mail entities.
pub type MailValidator = EntityValidator<Mail>;

/// Build a validator for Mail with all schema-defined field rules.
pub fn mail_validator() -> MailValidator {
    EntityValidator::new()
        .rule(NonNegative::new("interval_nbr", |e: &Mail| e.interval_nbr as i64))
        .rule(OptionalNotBlank::new("template_kind", |e: &Mail| e.template_kind.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
