//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod event_validator;
pub mod event_audit_log_validator;
pub mod event_type_validator;
pub mod mail_validator;
pub mod mail_registration_validator;
pub mod mail_slot_validator;
pub mod question_validator;
pub mod question_answer_validator;
pub mod registration_question_validator;
pub mod registration_validator;
pub mod registration_answer_validator;
pub mod slot_validator;
pub mod stage_validator;
pub mod tag_category_validator;
pub mod tag_validator;
pub mod ticket_validator;
pub mod type_mail_validator;

pub use event_validator::{EventValidator, event_validator};
pub use event_audit_log_validator::{EventAuditLogValidator, event_audit_log_validator};
pub use event_type_validator::{EventTypeValidator, event_type_validator};
pub use mail_validator::{MailValidator, mail_validator};
pub use mail_registration_validator::{MailRegistrationValidator, mail_registration_validator};
pub use mail_slot_validator::{MailSlotValidator, mail_slot_validator};
pub use question_validator::{QuestionValidator, question_validator};
pub use question_answer_validator::{QuestionAnswerValidator, question_answer_validator};
pub use registration_question_validator::{RegistrationQuestionValidator, registration_question_validator};
pub use registration_validator::{RegistrationValidator, registration_validator};
pub use registration_answer_validator::{RegistrationAnswerValidator, registration_answer_validator};
pub use slot_validator::{SlotValidator, slot_validator};
pub use stage_validator::{StageValidator, stage_validator};
pub use tag_category_validator::{TagCategoryValidator, tag_category_validator};
pub use tag_validator::{TagValidator, tag_validator};
pub use ticket_validator::{TicketValidator, ticket_validator};
pub use type_mail_validator::{TypeMailValidator, type_mail_validator};

// <<< CUSTOM
// END CUSTOM
