//! Validator for RegistrationAnswer entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<RegistrationAnswer>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::RegistrationAnswer;

/// Validator type alias for RegistrationAnswer entities.
pub type RegistrationAnswerValidator = EntityValidator<RegistrationAnswer>;

/// Build a validator for RegistrationAnswer with all schema-defined field rules.
pub fn registration_answer_validator() -> RegistrationAnswerValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("value_text", |e: &RegistrationAnswer| e.value_text.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
