//! Validator for RegistrationQuestion entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<RegistrationQuestion>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::RegistrationQuestion;

/// Validator type alias for RegistrationQuestion entities.
pub type RegistrationQuestionValidator = EntityValidator<RegistrationQuestion>;

/// Build a validator for RegistrationQuestion with all schema-defined field rules.
pub fn registration_question_validator() -> RegistrationQuestionValidator {
    EntityValidator::new()
        .rule(NonNegative::new("sequence", |e: &RegistrationQuestion| e.sequence as i64))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
