//! Validator for Slot entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Slot>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Slot;

/// Validator type alias for Slot entities.
pub type SlotValidator = EntityValidator<Slot>;

/// Build a validator for Slot with all schema-defined field rules.
pub fn slot_validator() -> SlotValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Slot| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
