//! Validator for TypeMail entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TypeMail>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::TypeMail;

/// Validator type alias for TypeMail entities.
pub type TypeMailValidator = EntityValidator<TypeMail>;

/// Build a validator for TypeMail with all schema-defined field rules.
pub fn type_mail_validator() -> TypeMailValidator {
    EntityValidator::new()
        .rule(NonNegative::new("interval_nbr", |e: &TypeMail| e.interval_nbr as i64))
        .rule(OptionalNotBlank::new("template_kind", |e: &TypeMail| e.template_kind.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
