//! Event Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Event exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use event::exports::{EventDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `EventDto` - Data transfer object for Event
/// - `EventSummary` - Summary view of Event
/// - `EventId` - Type-safe ID wrapper
/// - `EventAuditLogDto` - Data transfer object for EventAuditLog
/// - `EventAuditLogSummary` - Summary view of EventAuditLog
/// - `EventAuditLogId` - Type-safe ID wrapper
/// - `EventTypeDto` - Data transfer object for EventType
/// - `EventTypeSummary` - Summary view of EventType
/// - `EventTypeId` - Type-safe ID wrapper
/// - `MailDto` - Data transfer object for Mail
/// - `MailSummary` - Summary view of Mail
/// - `MailId` - Type-safe ID wrapper
/// - `MailRegistrationDto` - Data transfer object for MailRegistration
/// - `MailRegistrationSummary` - Summary view of MailRegistration
/// - `MailRegistrationId` - Type-safe ID wrapper
/// - `MailSlotDto` - Data transfer object for MailSlot
/// - `MailSlotSummary` - Summary view of MailSlot
/// - `MailSlotId` - Type-safe ID wrapper
/// - `QuestionDto` - Data transfer object for Question
/// - `QuestionSummary` - Summary view of Question
/// - `QuestionId` - Type-safe ID wrapper
/// - `QuestionAnswerDto` - Data transfer object for QuestionAnswer
/// - `QuestionAnswerSummary` - Summary view of QuestionAnswer
/// - `QuestionAnswerId` - Type-safe ID wrapper
/// - `RegistrationQuestionDto` - Data transfer object for RegistrationQuestion
/// - `RegistrationQuestionSummary` - Summary view of RegistrationQuestion
/// - `RegistrationQuestionId` - Type-safe ID wrapper
/// - `RegistrationDto` - Data transfer object for Registration
/// - `RegistrationSummary` - Summary view of Registration
/// - `RegistrationId` - Type-safe ID wrapper
/// - `RegistrationAnswerDto` - Data transfer object for RegistrationAnswer
/// - `RegistrationAnswerSummary` - Summary view of RegistrationAnswer
/// - `RegistrationAnswerId` - Type-safe ID wrapper
/// - `SlotDto` - Data transfer object for Slot
/// - `SlotSummary` - Summary view of Slot
/// - `SlotId` - Type-safe ID wrapper
/// - `StageDto` - Data transfer object for Stage
/// - `StageSummary` - Summary view of Stage
/// - `StageId` - Type-safe ID wrapper
/// - `TagCategoryDto` - Data transfer object for TagCategory
/// - `TagCategorySummary` - Summary view of TagCategory
/// - `TagCategoryId` - Type-safe ID wrapper
/// - `TagDto` - Data transfer object for Tag
/// - `TagSummary` - Summary view of Tag
/// - `TagId` - Type-safe ID wrapper
/// - `TicketDto` - Data transfer object for Ticket
/// - `TicketSummary` - Summary view of Ticket
/// - `TicketId` - Type-safe ID wrapper
/// - `TypeMailDto` - Data transfer object for TypeMail
/// - `TypeMailSummary` - Summary view of TypeMail
/// - `TypeMailId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `EventCreatedEvent` - Published when Event is created
/// - `EventUpdatedEvent` - Published when Event is updated
/// - `EventDeletedEvent` - Published when Event is deleted
/// - `EventAuditLogCreatedEvent` - Published when EventAuditLog is created
/// - `EventAuditLogUpdatedEvent` - Published when EventAuditLog is updated
/// - `EventAuditLogDeletedEvent` - Published when EventAuditLog is deleted
/// - `EventTypeCreatedEvent` - Published when EventType is created
/// - `EventTypeUpdatedEvent` - Published when EventType is updated
/// - `EventTypeDeletedEvent` - Published when EventType is deleted
/// - `MailCreatedEvent` - Published when Mail is created
/// - `MailUpdatedEvent` - Published when Mail is updated
/// - `MailDeletedEvent` - Published when Mail is deleted
/// - `MailRegistrationCreatedEvent` - Published when MailRegistration is created
/// - `MailRegistrationUpdatedEvent` - Published when MailRegistration is updated
/// - `MailRegistrationDeletedEvent` - Published when MailRegistration is deleted
/// - `MailSlotCreatedEvent` - Published when MailSlot is created
/// - `MailSlotUpdatedEvent` - Published when MailSlot is updated
/// - `MailSlotDeletedEvent` - Published when MailSlot is deleted
/// - `QuestionCreatedEvent` - Published when Question is created
/// - `QuestionUpdatedEvent` - Published when Question is updated
/// - `QuestionDeletedEvent` - Published when Question is deleted
/// - `QuestionAnswerCreatedEvent` - Published when QuestionAnswer is created
/// - `QuestionAnswerUpdatedEvent` - Published when QuestionAnswer is updated
/// - `QuestionAnswerDeletedEvent` - Published when QuestionAnswer is deleted
/// - `RegistrationQuestionCreatedEvent` - Published when RegistrationQuestion is created
/// - `RegistrationQuestionUpdatedEvent` - Published when RegistrationQuestion is updated
/// - `RegistrationQuestionDeletedEvent` - Published when RegistrationQuestion is deleted
/// - `RegistrationCreatedEvent` - Published when Registration is created
/// - `RegistrationUpdatedEvent` - Published when Registration is updated
/// - `RegistrationDeletedEvent` - Published when Registration is deleted
/// - `RegistrationAnswerCreatedEvent` - Published when RegistrationAnswer is created
/// - `RegistrationAnswerUpdatedEvent` - Published when RegistrationAnswer is updated
/// - `RegistrationAnswerDeletedEvent` - Published when RegistrationAnswer is deleted
/// - `SlotCreatedEvent` - Published when Slot is created
/// - `SlotUpdatedEvent` - Published when Slot is updated
/// - `SlotDeletedEvent` - Published when Slot is deleted
/// - `StageCreatedEvent` - Published when Stage is created
/// - `StageUpdatedEvent` - Published when Stage is updated
/// - `StageDeletedEvent` - Published when Stage is deleted
/// - `TagCategoryCreatedEvent` - Published when TagCategory is created
/// - `TagCategoryUpdatedEvent` - Published when TagCategory is updated
/// - `TagCategoryDeletedEvent` - Published when TagCategory is deleted
/// - `TagCreatedEvent` - Published when Tag is created
/// - `TagUpdatedEvent` - Published when Tag is updated
/// - `TagDeletedEvent` - Published when Tag is deleted
/// - `TicketCreatedEvent` - Published when Ticket is created
/// - `TicketUpdatedEvent` - Published when Ticket is updated
/// - `TicketDeletedEvent` - Published when Ticket is deleted
/// - `TypeMailCreatedEvent` - Published when TypeMail is created
/// - `TypeMailUpdatedEvent` - Published when TypeMail is updated
/// - `TypeMailDeletedEvent` - Published when TypeMail is deleted
pub struct ExportSummary;
