//! Public services for Event module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.


// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// The module's exported trait surface — the W8 seam contract (W8
// consumes ONLY this: seat availability reads, publication state,
// the guarded intake verb, the split's pair read, capability
// minting, the scheduler run verb; NEVER a second seat counter).
pub use crate::application::service::event_surface::{
    CapabilityScope, DefaultEventSurface, EventSurface, PublicationState, RegistrationStateView,
};
// The typed error surface + the verb services (in-process hosts).
pub use crate::application::service::event_error::{EventError, EventResult};
pub use crate::application::service::event_service::EventCommandService;
pub use crate::application::service::registration_service::RegistrationCommandService;
pub use crate::application::service::scheduler_service::SchedulerService;
pub use crate::application::service::seat_service::{SeatAvailability, SeatService};
// The exported route composers (the host mounts these; the module
// does not self-mount).
pub use crate::presentation::http::{
    event_admin_routes, event_intake_routes, event_public_routes, EventActor, EventAdminState,
    EventPublicState,
};
// <<< CUSTOM SERVICES END >>>
