//! Public types for Event module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// EVENT TYPES
// ============================================================================

/// Type-safe ID for Event
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EventId(pub Uuid);

impl EventId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EventId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EventId> for Uuid {
    fn from(id: EventId) -> Self {
        id.0
    }
}

/// Data transfer object for Event
///
/// This is the public representation of Event for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventDto {
    pub id: EventId,
    pub name: String,
    pub event_type_id: Option<Uuid>,
    pub stage_id: Uuid,
    pub kanban_state: EventKanbanState,
    pub date_begin: DateTime<Utc>,
    pub date_end: DateTime<Utc>,
    pub date_tz: String,
    pub is_multi_slots: bool,
    pub event_slot_count: i32,
    pub seats_limited: bool,
    pub seats_max: i32,
    pub address_id: Option<Uuid>,
    pub organizer_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub event_url: Option<String>,
    pub badge_format: EventBadgeFormat,
    pub is_published: bool,
    pub date_publish: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Event for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventSummary {
    pub id: EventId,
    pub name: String,
}

/// Reference to Event for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventRef {
    pub id: EventId,
}

// ============================================================================
// EVENTAUDITLOG TYPES
// ============================================================================

/// Type-safe ID for EventAuditLog
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EventAuditLogId(pub Uuid);

impl EventAuditLogId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EventAuditLogId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EventAuditLogId> for Uuid {
    fn from(id: EventAuditLogId) -> Self {
        id.0
    }
}

/// Data transfer object for EventAuditLog
///
/// This is the public representation of EventAuditLog for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventAuditLogDto {
    pub id: EventAuditLogId,
    pub event: EventAuditEvent,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub detail: Option<serde_json::Value>,
    pub occurred_at: DateTime<Utc>,
}

/// Summary view of EventAuditLog for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventAuditLogSummary {
    pub id: EventAuditLogId,
}

/// Reference to EventAuditLog for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventAuditLogRef {
    pub id: EventAuditLogId,
}

// ============================================================================
// EVENTTYPE TYPES
// ============================================================================

/// Type-safe ID for EventType
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EventTypeId(pub Uuid);

impl EventTypeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EventTypeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EventTypeId> for Uuid {
    fn from(id: EventTypeId) -> Self {
        id.0
    }
}

/// Data transfer object for EventType
///
/// This is the public representation of EventType for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventTypeDto {
    pub id: EventTypeId,
    pub name: String,
    pub description: Option<String>,
    pub seats_limited: bool,
    pub seats_max: i32,
    pub default_date_tz: String,
    pub is_multi_slots: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of EventType for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventTypeSummary {
    pub id: EventTypeId,
    pub name: String,
}

/// Reference to EventType for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventTypeRef {
    pub id: EventTypeId,
}

// ============================================================================
// MAIL TYPES
// ============================================================================

/// Type-safe ID for Mail
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MailId(pub Uuid);

impl MailId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for MailId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<MailId> for Uuid {
    fn from(id: MailId) -> Self {
        id.0
    }
}

/// Data transfer object for Mail
///
/// This is the public representation of Mail for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailDto {
    pub id: MailId,
    pub event_id: Uuid,
    pub interval_nbr: i32,
    pub interval_unit: EventIntervalUnit,
    pub interval_kind: EventIntervalKind,
    pub notification_channel: EventNotificationChannel,
    pub scheduled_date: Option<DateTime<Utc>>,
    pub mail_done: bool,
    pub last_registration_id: Option<Uuid>,
    pub template_ref: Option<Uuid>,
    pub template_kind: Option<String>,
    pub error_datetime: Option<DateTime<Utc>>,
    pub error_kind: Option<EventMailErrorKind>,
    pub metadata: serde_json::Value,
}

/// Summary view of Mail for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailSummary {
    pub id: MailId,
}

/// Reference to Mail for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailRef {
    pub id: MailId,
}

// ============================================================================
// MAILREGISTRATION TYPES
// ============================================================================

/// Type-safe ID for MailRegistration
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MailRegistrationId(pub Uuid);

impl MailRegistrationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for MailRegistrationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<MailRegistrationId> for Uuid {
    fn from(id: MailRegistrationId) -> Self {
        id.0
    }
}

/// Data transfer object for MailRegistration
///
/// This is the public representation of MailRegistration for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailRegistrationDto {
    pub id: MailRegistrationId,
    pub scheduler_id: Uuid,
    pub registration_id: Uuid,
    pub scheduled_date: Option<DateTime<Utc>>,
    pub mail_sent: bool,
    pub outcome: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of MailRegistration for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailRegistrationSummary {
    pub id: MailRegistrationId,
}

/// Reference to MailRegistration for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailRegistrationRef {
    pub id: MailRegistrationId,
}

// ============================================================================
// MAILSLOT TYPES
// ============================================================================

/// Type-safe ID for MailSlot
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MailSlotId(pub Uuid);

impl MailSlotId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for MailSlotId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<MailSlotId> for Uuid {
    fn from(id: MailSlotId) -> Self {
        id.0
    }
}

/// Data transfer object for MailSlot
///
/// This is the public representation of MailSlot for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailSlotDto {
    pub id: MailSlotId,
    pub scheduler_id: Uuid,
    pub slot_id: Uuid,
    pub scheduled_date: Option<DateTime<Utc>>,
    pub mail_done: bool,
    pub last_registration_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of MailSlot for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailSlotSummary {
    pub id: MailSlotId,
}

/// Reference to MailSlot for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MailSlotRef {
    pub id: MailSlotId,
}

// ============================================================================
// QUESTION TYPES
// ============================================================================

/// Type-safe ID for Question
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QuestionId(pub Uuid);

impl QuestionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QuestionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QuestionId> for Uuid {
    fn from(id: QuestionId) -> Self {
        id.0
    }
}

/// Data transfer object for Question
///
/// This is the public representation of Question for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionDto {
    pub id: QuestionId,
    pub question: String,
    pub question_kind: EventQuestionKind,
    pub is_default: bool,
    pub is_reusable: bool,
    pub once_per_order: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of Question for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionSummary {
    pub id: QuestionId,
}

/// Reference to Question for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionRef {
    pub id: QuestionId,
}

// ============================================================================
// QUESTIONANSWER TYPES
// ============================================================================

/// Type-safe ID for QuestionAnswer
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QuestionAnswerId(pub Uuid);

impl QuestionAnswerId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QuestionAnswerId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QuestionAnswerId> for Uuid {
    fn from(id: QuestionAnswerId) -> Self {
        id.0
    }
}

/// Data transfer object for QuestionAnswer
///
/// This is the public representation of QuestionAnswer for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionAnswerDto {
    pub id: QuestionAnswerId,
    pub question_id: Uuid,
    pub name: String,
    pub sequence: i32,
    pub metadata: serde_json::Value,
}

/// Summary view of QuestionAnswer for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionAnswerSummary {
    pub id: QuestionAnswerId,
    pub name: String,
}

/// Reference to QuestionAnswer for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionAnswerRef {
    pub id: QuestionAnswerId,
}

// ============================================================================
// REGISTRATIONQUESTION TYPES
// ============================================================================

/// Type-safe ID for RegistrationQuestion
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RegistrationQuestionId(pub Uuid);

impl RegistrationQuestionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RegistrationQuestionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RegistrationQuestionId> for Uuid {
    fn from(id: RegistrationQuestionId) -> Self {
        id.0
    }
}

/// Data transfer object for RegistrationQuestion
///
/// This is the public representation of RegistrationQuestion for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistrationQuestionDto {
    pub id: RegistrationQuestionId,
    pub event_id: Option<Uuid>,
    pub event_type_id: Option<Uuid>,
    pub question_id: Uuid,
    pub sequence: i32,
    pub metadata: serde_json::Value,
}

/// Summary view of RegistrationQuestion for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistrationQuestionSummary {
    pub id: RegistrationQuestionId,
}

/// Reference to RegistrationQuestion for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistrationQuestionRef {
    pub id: RegistrationQuestionId,
}

// ============================================================================
// REGISTRATION TYPES
// ============================================================================

/// Type-safe ID for Registration
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RegistrationId(pub Uuid);

impl RegistrationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RegistrationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RegistrationId> for Uuid {
    fn from(id: RegistrationId) -> Self {
        id.0
    }
}

/// Data transfer object for Registration
///
/// This is the public representation of Registration for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistrationDto {
    pub id: RegistrationId,
    pub event_id: Uuid,
    pub event_slot_id: Option<Uuid>,
    pub event_ticket_id: Option<Uuid>,
    pub name: String,
    pub email: String,
    pub phone: Option<String>,
    pub company_name: Option<String>,
    pub partner_id: Option<Uuid>,
    pub state: EventRegistrationState,
    pub date_closed: Option<DateTime<Utc>>,
    pub sale_order_id: Option<Uuid>,
    pub sale_order_state: Option<EventSaleOrderState>,
    pub sale_status: Option<EventSaleStatus>,
    pub active: bool,
    pub barcode: String,
    pub company_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Registration for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistrationSummary {
    pub id: RegistrationId,
    pub name: String,
    pub email: String,
    pub company_name: Option<String>,
}

/// Reference to Registration for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistrationRef {
    pub id: RegistrationId,
}

// ============================================================================
// REGISTRATIONANSWER TYPES
// ============================================================================

/// Type-safe ID for RegistrationAnswer
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RegistrationAnswerId(pub Uuid);

impl RegistrationAnswerId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RegistrationAnswerId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RegistrationAnswerId> for Uuid {
    fn from(id: RegistrationAnswerId) -> Self {
        id.0
    }
}

/// Data transfer object for RegistrationAnswer
///
/// This is the public representation of RegistrationAnswer for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistrationAnswerDto {
    pub id: RegistrationAnswerId,
    pub registration_id: Uuid,
    pub question_id: Uuid,
    pub value_text: Option<String>,
    pub value_answer_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of RegistrationAnswer for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistrationAnswerSummary {
    pub id: RegistrationAnswerId,
}

/// Reference to RegistrationAnswer for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistrationAnswerRef {
    pub id: RegistrationAnswerId,
}

// ============================================================================
// SLOT TYPES
// ============================================================================

/// Type-safe ID for Slot
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SlotId(pub Uuid);

impl SlotId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SlotId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SlotId> for Uuid {
    fn from(id: SlotId) -> Self {
        id.0
    }
}

/// Data transfer object for Slot
///
/// This is the public representation of Slot for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlotDto {
    pub id: SlotId,
    pub event_id: Uuid,
    pub name: String,
    pub date_begin: DateTime<Utc>,
    pub date_end: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Slot for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlotSummary {
    pub id: SlotId,
    pub name: String,
}

/// Reference to Slot for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlotRef {
    pub id: SlotId,
}

// ============================================================================
// STAGE TYPES
// ============================================================================

/// Type-safe ID for Stage
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct StageId(pub Uuid);

impl StageId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for StageId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<StageId> for Uuid {
    fn from(id: StageId) -> Self {
        id.0
    }
}

/// Data transfer object for Stage
///
/// This is the public representation of Stage for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StageDto {
    pub id: StageId,
    pub name: String,
    pub sequence: i32,
    pub fold: bool,
    pub pipe_end: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of Stage for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StageSummary {
    pub id: StageId,
    pub name: String,
}

/// Reference to Stage for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StageRef {
    pub id: StageId,
}

// ============================================================================
// TAGCATEGORY TYPES
// ============================================================================

/// Type-safe ID for TagCategory
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TagCategoryId(pub Uuid);

impl TagCategoryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TagCategoryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TagCategoryId> for Uuid {
    fn from(id: TagCategoryId) -> Self {
        id.0
    }
}

/// Data transfer object for TagCategory
///
/// This is the public representation of TagCategory for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCategoryDto {
    pub id: TagCategoryId,
    pub name: String,
    pub metadata: serde_json::Value,
}

/// Summary view of TagCategory for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCategorySummary {
    pub id: TagCategoryId,
    pub name: String,
}

/// Reference to TagCategory for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCategoryRef {
    pub id: TagCategoryId,
}

// ============================================================================
// TAG TYPES
// ============================================================================

/// Type-safe ID for Tag
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TagId(pub Uuid);

impl TagId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TagId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TagId> for Uuid {
    fn from(id: TagId) -> Self {
        id.0
    }
}

/// Data transfer object for Tag
///
/// This is the public representation of Tag for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagDto {
    pub id: TagId,
    pub name: String,
    pub category_id: Option<Uuid>,
    pub color: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Tag for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagSummary {
    pub id: TagId,
    pub name: String,
}

/// Reference to Tag for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagRef {
    pub id: TagId,
}

// ============================================================================
// TICKET TYPES
// ============================================================================

/// Type-safe ID for Ticket
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TicketId(pub Uuid);

impl TicketId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TicketId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TicketId> for Uuid {
    fn from(id: TicketId) -> Self {
        id.0
    }
}

/// Data transfer object for Ticket
///
/// This is the public representation of Ticket for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketDto {
    pub id: TicketId,
    pub event_id: Uuid,
    pub name: String,
    pub seats_max: i32,
    pub seats_max_per_order: i32,
    pub start_sale_datetime: Option<DateTime<Utc>>,
    pub end_sale_datetime: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Ticket for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketSummary {
    pub id: TicketId,
    pub name: String,
}

/// Reference to Ticket for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketRef {
    pub id: TicketId,
}

// ============================================================================
// TYPEMAIL TYPES
// ============================================================================

/// Type-safe ID for TypeMail
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TypeMailId(pub Uuid);

impl TypeMailId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TypeMailId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TypeMailId> for Uuid {
    fn from(id: TypeMailId) -> Self {
        id.0
    }
}

/// Data transfer object for TypeMail
///
/// This is the public representation of TypeMail for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeMailDto {
    pub id: TypeMailId,
    pub event_type_id: Uuid,
    pub interval_nbr: i32,
    pub interval_unit: EventIntervalUnit,
    pub interval_kind: EventIntervalKind,
    pub notification_channel: EventNotificationChannel,
    pub template_ref: Option<Uuid>,
    pub template_kind: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of TypeMail for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeMailSummary {
    pub id: TypeMailId,
}

/// Reference to TypeMail for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeMailRef {
    pub id: TypeMailId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
